export {
  type ArrayCallbackContainerCallKind,
  type ArrayMethodAccessKind,
  type ArrayMethodCallSiteInfo,
  type ArrayMethodFamilyName,
  type ArrayMethodOwnership,
  type ArrayMethodResultSinkCallInfo,
  type ArrayMethodResultSinkReceiverChainCallInfo,
  type CallKind,
  classifyArrayCallbackContainerCall,
  classifyArrayMethodAccess,
  classifyArrayMethodCall,
  classifyArrayMethodCallSite,
  classifyArrayMethodResultSinkCall,
  classifyArrayMethodResultSinkReceiverChainCall,
  classifyLegacyPatternCarrier,
  classifyWildcardTraversalCall,
  detectCallKind,
  detectDirectBuilderCall,
  detectNewExpressionKind,
  findEnclosingPatternBuilderCallbackDescriptor,
  FUNCTION_HARDENING_HELPER_PREFIX,
  getCapabilitySummaryCallbackArgument,
  getLiftAppliedInnerCall,
  getLiftAppliedInputAndCallback,
  getLoweredArrayMethodName,
  getPatternBuilderCallbackArgument,
  getPatternBuilderCallbackDescriptor,
  hasReactiveCollectionProvenance,
  isConsumedByTerminalChainCall,
  isPatternBuilderCall,
  isReactiveOriginCall,
  isReactiveOriginExpression,
  isReactiveOriginTaggedTemplate,
  isReactiveValueExpression,
  isReactiveValueSymbol,
  isSimpleReactiveAccessExpression,
  isWildcardTraversalCall,
  type LegacyPatternCarrierKind,
  type PatternBuilderCallbackDescriptor,
  updatePatternBuilderCallbackArgument,
} from "./call-kind.ts";
export * from "./dataflow.ts";
export {
  classifyFactoryCallee,
  classifyFactoryCallExposure,
  classifyFactoryCallTarget,
  type FactoryCalleeClassification,
  type FactoryCallExposure,
  type FactoryCallTargetClassification,
  type FactoryValueOrigin,
  isFactoryModifierAccess,
  isInsideFactoryMaterializationBoundary,
} from "./factory-callee.ts";
export {
  classifyReactiveContext,
  findEnclosingCallbackContext,
  isInRestrictedReactiveContext,
  isInsideRestrictedContext,
  isInsideSafeCallbackWrapper,
  isInsideSafeWrapper,
  isStandaloneFunctionDefinition,
  type ReactiveContextInfo,
  type ReactiveContextKind,
  type ReactiveContextLookup,
  type ReactiveContextOwner,
  RESTRICTED_CONTEXT_BUILDERS,
  SAFE_WRAPPER_BUILDERS,
} from "./reactive-context.ts";
export * from "./normalize.ts";
export {
  isEventHandlerJsxAttribute,
  isEventHandlerType,
  isSafeEventHandlerCall,
} from "./event-handlers.ts";
export {
  getEnclosingFunctionLikeDeclaration,
  isFunctionLikeExpression,
} from "./function-predicates.ts";
export {
  getExpressionText,
  getMemberSymbol,
  getMethodCallTarget,
  getNodeText,
  getTypeAtLocationWithFallback,
  getVariableInitializer,
  isFunctionParameter,
  isMethodCall,
  isOptionalMemberSymbol,
  preserveLineage,
  preserveSourceMapRange,
  setParentPointers,
  visitEachChildWithJsx,
} from "./utils.ts";
export {
  ensureTypeNodeRegistered,
  getTypeFromTypeNodeWithFallback,
  getTypeReferenceArgument,
  hasArrayTypeArgument,
  inferContextualType,
  inferParameterType,
  inferReturnType,
  inferWidenedTypeFromExpression,
  isAnyOrUnknownType,
  isAnyType,
  isCellLikeType,
  isCollectionType,
  isUnknownType,
  isUnresolvedSchemaType,
  registerSyntheticCallType,
  typeToSchemaTypeNode,
  typeToTypeNode,
  unwrapCellLikeType,
  unwrapOpaqueLikeType,
  widenLiteralType,
} from "./type-inference.ts";
export {
  qualifyCommonFabricTypeRefs,
  typeToTypeNodeWithRegistry,
} from "./type-building.ts";
