export {
  type ArrayCallbackContainerCallKind,
  type ArrayMethodAccessKind,
  type ArrayMethodCallSiteInfo,
  type ArrayMethodFamilyName,
  type ArrayMethodOwnership,
  type ArrayMethodResultSinkCallInfo,
  type ArrayMethodResultSinkReceiverChainCallInfo,
  type CallKind,
  classifyArrayCallbackContainerCall,
  classifyArrayMethodAccess,
  classifyArrayMethodCall,
  classifyArrayMethodCallSite,
  classifyArrayMethodResultSinkCall,
  classifyArrayMethodResultSinkReceiverChainCall,
  classifyWildcardTraversalCall,
  detectCallKind,
  detectDirectBuilderCall,
  getCapabilitySummaryCallbackArgument,
  getDeriveInputAndCallbackArgument,
  getLoweredArrayMethodName,
  getPatternBuilderCallbackArgument,
  hasReactiveCollectionProvenance,
  isConsumedByTerminalChainCall,
  isPatternBuilderCall,
  isReactiveOriginCall,
  isReactiveValueExpression,
  isReactiveValueSymbol,
  isSimpleReactiveAccessExpression,
  isWildcardTraversalCall,
} from "./call-kind.ts";
export * from "./dataflow.ts";
export {
  classifyReactiveContext,
  findEnclosingCallbackContext,
  isInRestrictedReactiveContext,
  isInsideRestrictedContext,
  isInsideSafeCallbackWrapper,
  isInsideSafeWrapper,
  isStandaloneFunctionDefinition,
  type ReactiveContextInfo,
  type ReactiveContextKind,
  type ReactiveContextLookup,
  type ReactiveContextOwner,
  RESTRICTED_CONTEXT_BUILDERS,
  SAFE_WRAPPER_BUILDERS,
} from "./reactive-context.ts";
export * from "./normalize.ts";
export {
  isEventHandlerJsxAttribute,
  isEventHandlerType,
  isSafeEventHandlerCall,
} from "./event-handlers.ts";
export {
  getEnclosingFunctionLikeDeclaration,
  isFunctionLikeExpression,
} from "./function-predicates.ts";
export {
  getExpressionText,
  getMemberSymbol,
  getMethodCallTarget,
  getTypeAtLocationWithFallback,
  getVariableInitializer,
  isFunctionParameter,
  isMethodCall,
  isOptionalMemberSymbol,
  setParentPointers,
  visitEachChildWithJsx,
} from "./utils.ts";
export {
  ensureTypeNodeRegistered,
  getTypeFromTypeNodeWithFallback,
  getTypeReferenceArgument,
  hasArrayTypeArgument,
  inferContextualType,
  inferParameterType,
  inferReturnType,
  inferWidenedTypeFromExpression,
  isAnyOrUnknownType,
  isAnyType,
  isCellLikeType,
  isUnknownType,
  isUnresolvedSchemaType,
  registerSyntheticCallType,
  typeToSchemaTypeNode,
  typeToTypeNode,
  unwrapCellLikeType,
  unwrapOpaqueLikeType,
  widenLiteralType,
} from "./type-inference.ts";
