// Generated by tasks/build-binaries.ts; do not edit by hand.
//
// Version axis of the durable compile cache: the `<version>` segment of
// `compileCache:<version>/<identity>` keys. The committed value is the
// from-source sentinel; the binary build overwrites it with a hash of the
// compiler inputs before `deno compile`, then restores the sentinel. See
// compiler-fingerprint.deno.ts for the fingerprint and input set.
export const COMPILE_CACHE_RUNTIME_VERSION = "cf/esm-compile/source";
