import { isObject, isRecord } from "@commontools/utils/types";
import {
  type Cell,
  getTopFrame,
  ID,
  ID_FIELD,
  isStreamAlias,
  type JSONSchema,
  type Schema,
} from "@commontools/builder";
import { type DeepKeyLookup, type DocImpl, isDoc } from "./doc.ts";
import { getEntityId } from "./doc-map.ts";
import {
  createQueryResultProxy,
  type QueryResult,
} from "./query-result-proxy.ts";
import {
  diffAndUpdate,
  resolveLinkToAlias,
  resolveLinkToValue,
} from "./utils.ts";
import type { ReactivityLog } from "./scheduler.ts";
import { type EntityId } from "./doc-map.ts";
import { type Cancel, isCancel, useCancelGroup } from "./cancel.ts";
import { validateAndTransform } from "./schema.ts";

/**
 * This is the regular Cell interface, generated by DocImpl.asCell().
 *
 * This abstracts away the paths behind an interface that e.g. the UX code or
 * modules that prefer cell interfaces can use.
 *
 * These methods are available in the system and in spell code:
 *
 * @method get Returns the current value of the cell.
 * @returns {T}
 *
 * @method set Alias for `send`. Sets a new value for the cell.
 * @method send Sets a new value for the cell.
 * @param {T} value - The new value to set.
 * @returns {void}
 *
 * @method update Updates multiple properties of an object cell at once.
 * @param {Partial<T>} values - The properties to update.
 * @returns {void}
 *
 * @method push Adds an item to the end of an array cell.
 * @param {U | DocImpl<U> | CellLink} value - The value to add, where U is the
 * array element type.
 * @returns {void}
 *
 * @method equals Compares two cells for equality.
 * @param {Cell<any>} other - The cell to compare with.
 * @returns {boolean}
 *
 * @method key Returns a new cell for the specified key path.
 * @param {K} valueKey - The key to access in the cell's value.
 * @returns {Cell<T[K]>}
 *
 * Everything below is only available in the system, not in spell code:
 *
 * @method asSchema Creates a new cell with a specific schema.
 * @param {JSONSchema} schema - The schema to apply.
 * @returns {Cell<T>} - A cell with the specified schema.
 *
 * @method withLog Creates a new cell with a specific reactivity log.
 * @param {ReactivityLog} log - The log to use.
 * @returns {Cell<T>}
 *
 * @method sink Adds a callback that is called immediately and on cell changes.
 * @param {function} callback - The callback to be called when the cell changes.
 * @returns {function} - A function to Cleanup the callback.
 *
 * @method getAsQueryResult Returns a query result for the cell.
 * @param {Path} path - The optional path to follow.
 * @param {ReactivityLog} log - Optional reactivity log.
 * @returns {QueryResult<DeepKeyLookup<T, Path>>}
 *
 * @method getAsCellLink Returns a cell link for the cell.
 * @returns {CellLink}
 *
 * @method getSourceCell Returns the source cell with optional schema.
 * @param {JSONSchema} schema - Optional schema to apply.
 * @returns {Cell<T & {[TYPE]: string | undefined} & {argument: any}>}
 *
 * @method toJSON Returns a serializable cell link (not the contents) to the
 * cell. This is used e.g. when creating merkle references that refer to cells.
 * It currentlly doesn't contain the space. We'll eventually want to get a
 * relative link here, but that will require context toJSON doesn't get.
 * @returns {{cell: {"/": string} | undefined, path: PropertyKey[]}}
 *
 * @property entityId Returns the current entity ID of the cell.
 * @returns {EntityId | undefined}
 *
 * @property schema Optional schema for the cell.
 * @returns {JSONSchema | undefined}
 *
 * @property rootSchema Optional root schema for cell's schema. This differs
 * from `schema` when the cell represents a child of the original cell (e.g. via
 * `key()`). We need to keep the root schema to resolve `$ref` in the schema.
 * @returns {JSONSchema | undefined}
 *
 * The following are just for debugging and might disappear: (This allows
 * clicking on a property in the debugger and getting the value)
 *
 * @method value Returns the current value of the cell.
 * @returns {T}
 *
 * @property cellLink The cell link representing this cell.
 * @returns {CellLink}
 */
declare module "@commontools/builder/interface" {
  interface Cell<T> {
    get(): T;
    set(value: Cellify<T> | T): void;
    send(value: Cellify<T> | T): void;
    update<V extends Cellify<Partial<T> | Partial<T>>>(
      values: V extends object ? V : never,
    ): void;
    push(
      ...value: Array<
        | (T extends Array<infer U> ? (Cellify<U> | U | DocImpl<U>) : any)
        | CellLink
      >
    ): void;
    equals(other: Cell<any>): boolean;
    key<K extends T extends Cell<infer S> ? keyof S : keyof T>(
      valueKey: K,
    ): Cell<
      T extends Cell<infer S> ? S[K & keyof S] : T[K] extends never ? any : T[K]
    >;

    asSchema<T>(
      schema?: JSONSchema,
    ): Cell<T>;
    asSchema<S extends JSONSchema = JSONSchema>(
      schema: S,
    ): Cell<Schema<S>>;
    withLog(log: ReactivityLog): Cell<T>;
    sink(callback: (value: T) => Cancel | undefined | void): Cancel;
    getAsQueryResult<Path extends PropertyKey[]>(
      path?: Path,
      log?: ReactivityLog,
    ): QueryResult<DeepKeyLookup<T, Path>>;
    getAsCellLink(): CellLink;
    getDoc(): DocImpl<any>;
    getSourceCell<T>(
      schema?: JSONSchema,
    ): Cell<
      & T
      // Add default types for TYPE and `argument`. A more specific type in T will
      // take precedence.
      & { [TYPE]: string | undefined }
      & ("argument" extends keyof T ? unknown : { argument: any })
    >;
    getSourceCell<S extends JSONSchema = JSONSchema>(
      schema: S,
    ): Cell<
      & Schema<S>
      // Add default types for TYPE and `argument`. A more specific type in
      // `schema` will take precedence.
      & { [TYPE]: string | undefined }
      & ("argument" extends keyof Schema<S> ? unknown
        : { argument: any })
    >;
    toJSON(): { cell: { "/": string } | undefined; path: PropertyKey[] };
    schema?: JSONSchema;
    rootSchema?: JSONSchema;
    value: T;
    cellLink: CellLink;
    entityId: EntityId | undefined;
    [isCellMarker]: true;
    copyTrap: boolean;
  }
}

export type { Cell } from "@commontools/builder/interface";

/**
 * Cellify is a type utility that allows any part of type T to be wrapped in
 * Cell<>, and allow any part of T that is currently wrapped in Cell<> to be
 * used unwrapped. This is designed for use with Cell<T> method parameters,
 * allowing flexibility in how values are passed.
 */
export type Cellify<T> =
  // Handle existing Cell<> types, allowing unwrapping
  T extends Cell<infer U> ? Cellify<U> | Cell<Cellify<U>>
    // Handle arrays
    : T extends Array<infer U> ? Array<Cellify<U>> | Cell<Array<Cellify<U>>>
    // Handle objects (excluding null), adding optional ID fields
    : T extends object ?
        | ({ [K in keyof T]: Cellify<T[K]> } & { [ID]?: any; [ID_FIELD]?: any })
        | Cell<
          { [K in keyof T]: Cellify<T[K]> } & { [ID]?: any; [ID_FIELD]?: any }
        >
    // Handle primitives
    : T | Cell<T>;

export interface Stream<T> {
  send(event: T): void;
  sink(callback: (event: T) => Cancel | undefined | void): Cancel;
  getDoc(): DocImpl<any>;
  schema?: JSONSchema;
  rootSchema?: JSONSchema;
  [isStreamMarker]: true;
}

/**
 * Cell link.
 *
 * A cell link is a doc and a path within that doc.
 */
export type CellLink = {
  space?: string;
  cell: DocImpl<any>;
  path: PropertyKey[];
  schema?: JSONSchema;
  rootSchema?: JSONSchema;
};

export function createCell<T>(
  doc: DocImpl<any>,
  path: PropertyKey[] = [],
  log?: ReactivityLog,
  schema?: JSONSchema,
  rootSchema: JSONSchema | undefined = schema,
): Cell<T> {
  // Resolve the path to check whether it's a stream. We're not logging this right now.
  // The corner case where during it's lifetime this changes from non-stream to stream
  // or vice versa will not be detected.
  const ref = resolveLinkToValue(doc, path, undefined, schema, rootSchema);
  // Use schema from alias if provided and no explicit schema was set
  if (!schema && ref.schema) {
    schema = ref.schema;
    rootSchema = ref.rootSchema || ref.schema;
  }

  if (isStreamAlias(ref.cell.getAtPath(ref.path))) {
    return createStreamCell(
      ref.cell,
      ref.path,
      log,
      schema,
      rootSchema,
    ) as unknown as Cell<T>;
  } else {
    return createRegularCell(doc, path, log, schema, rootSchema);
  }
}

function createStreamCell<T>(
  doc: DocImpl<any>,
  path: PropertyKey[],
  _log?: ReactivityLog,
  schema?: JSONSchema,
  rootSchema?: JSONSchema,
): Stream<T> {
  const listeners = new Set<(event: T) => Cancel | undefined>();

  let cleanup: Cancel | undefined;

  const self: Stream<T> = {
    // Implementing just the subset of Cell<T> that is needed for streams.
    send: (event: T) => {
      // Use runtime from doc if available
      if (doc.runtime) {
        doc.runtime.scheduler.queueEvent({ cell: doc, path }, event);
      } else {
        throw new Error("No runtime available for queueEvent");
      }

      cleanup?.();
      const [cancel, addCancel] = useCancelGroup();
      cleanup = cancel;

      listeners.forEach((callback) => addCancel(callback(event)));
    },
    sink: (callback: (value: T) => Cancel | undefined): Cancel => {
      listeners.add(callback);
      return () => listeners.delete(callback);
    },
    getDoc: () => doc,
    schema,
    rootSchema,
    [isStreamMarker]: true,
  } satisfies Stream<T>;

  return self;
}

function createRegularCell<T>(
  doc: DocImpl<any>,
  path: PropertyKey[],
  log?: ReactivityLog,
  schema?: JSONSchema,
  rootSchema?: JSONSchema,
): Cell<T> {
  const self = {
    get: () => validateAndTransform(doc, path, schema, log, rootSchema),
    set: (newValue: Cellify<T>) =>
      // TODO(@ubik2) investigate whether i need to check classified as i walk down my own obj
      diffAndUpdate(
        resolveLinkToAlias(doc, path, log, schema, rootSchema),
        newValue,
        log,
        getTopFrame()?.cause,
      ),
    send: (newValue: Cellify<T>) => self.set(newValue),
    update: (values: Cellify<Partial<T>>) => {
      if (!isRecord(values)) {
        throw new Error("Can't update with non-object value");
      }
      for (const [key, value] of Object.entries(values)) {
        // Workaround for type checking, since T can be Cell<> and that's fine.
        (self.key as any)(key).set(value);
      }
    },
    push: (
      ...values: Array<
        | (T extends Array<infer U> ? (Cellify<U> | U | DocImpl<U>) : any)
        | CellLink
      >
    ) => {
      // Follow aliases and references, since we want to get to an assumed
      // existing array.
      const ref = resolveLinkToValue(doc, path, log, schema, rootSchema);
      const cause = getTopFrame()?.cause;

      let array = ref.cell.getAtPath(ref.path);
      if (array !== undefined && !Array.isArray(array)) {
        throw new Error("Can't push into non-array value");
      }

      // If this is an object and it doesn't have an ID, add one.
      const valuesToWrite = values.map((value: any) => {
        if (
          !isCell(value) && !isCellLink(value) && !isDoc(value) &&
          isObject(value) &&
          (value as { [ID]?: unknown })[ID] === undefined && getTopFrame()
        ) {
          return {
            [ID]: getTopFrame()!.generatedIdCounter++,
            ...value,
          };
        } else {
          return value;
        }
      });

      // If there is no array yet, create it first. We have to do this as a
      // separate operation, so that in the next steps [ID] is properly anchored
      // in the array.
      if (array === undefined) {
        diffAndUpdate(ref, [], log, cause);
        array = Array.isArray(schema?.default) ? schema.default : [];
      }

      // Append the new values to the array.
      diffAndUpdate(ref, [...array, ...valuesToWrite], log, cause);

      const appended = ref.cell.getAtPath(ref.path).slice(
        -valuesToWrite.length,
      );

      // Hacky retry logic for push only. See storage.ts for details on this
      // retry approach and what we should really be doing instead.
      if (!ref.cell.retry) ref.cell.retry = [];
      ref.cell.retry.push((newBaseValue) => {
        // Unlikely, but maybe the conflict reset to undefined?
        if (!Array.isArray(newBaseValue)) {
          newBaseValue = Array.isArray(schema?.default) ? schema.default : [];
        }

        // Serialize cell links that were appended during the push. This works
        // because of the .toJSON() method on Cell.
        const newValues = JSON.parse(JSON.stringify(appended));

        // Reappend the new values.
        return [...(newBaseValue as unknown[]), ...newValues];
      });
    },
    equals: (other: Cell<any>) =>
      JSON.stringify(self) === JSON.stringify(other),
    key: <K extends T extends Cell<infer S> ? keyof S : keyof T>(
      valueKey: K,
    ): T extends Cell<infer S> ? Cell<S[K & keyof S]> : Cell<T[K]> => {
      const childSchema = doc.runtime.cfc.getSchemaAtPath(
        schema,
        [valueKey.toString()],
        rootSchema,
      );
      return createCell(
        doc,
        [...path, valueKey],
        log,
        childSchema,
        rootSchema,
      ) as T extends Cell<infer S> ? Cell<S[K & keyof S]> : Cell<T[K]>;
    },

    asSchema: (newSchema?: JSONSchema) =>
      createCell(doc, path, log, newSchema, newSchema),
    withLog: (newLog: ReactivityLog) =>
      createCell(doc, path, newLog, schema, rootSchema),
    sink: (callback: (value: T) => Cancel | undefined) =>
      subscribeToReferencedDocs(callback, doc, path, schema, rootSchema),
    getAsQueryResult: (subPath: PropertyKey[] = [], newLog?: ReactivityLog) =>
      createQueryResultProxy(doc, [...path, ...subPath], newLog ?? log),
    getAsCellLink: () => // Add space here, so that JSON.stringify() of this retains the space.
    ({ space: doc.space, cell: doc, path, schema, rootSchema }),
    getDoc: () => doc,
    getSourceCell: (newSchema?: JSONSchema) =>
      doc.sourceCell?.asCell([], log, newSchema, newSchema) as Cell<any>,
    toJSON: () =>
      // TODO(seefeld): Should this include the schema, as cells are defiined by doclink & schema?
      ({ cell: doc.toJSON(), path }) satisfies {
        cell: { "/": string } | undefined;
        path: PropertyKey[];
      },
    get value(): T {
      return self.get();
    },
    get cellLink(): CellLink {
      return { space: doc.space, cell: doc, path, schema, rootSchema };
    },
    get entityId(): EntityId | undefined {
      return getEntityId(self.getAsCellLink());
    },
    [isCellMarker]: true,
    get copyTrap(): boolean {
      throw new Error(
        "Copy trap: Don't copy renderer cells. Create references instead.",
      );
    },
    schema,
    rootSchema,
  } as Cell<T>;

  return self;
}

function subscribeToReferencedDocs<T>(
  callback: (value: T) => Cancel | undefined,
  doc: DocImpl<any>,
  path: PropertyKey[],
  schema: JSONSchema | undefined,
  rootSchema: JSONSchema | undefined,
): Cancel {
  const initialLog = {
    reads: [],
    writes: [],
  } satisfies ReactivityLog;
  // Get the value once to determine all the docs that need to be subscribed to.
  const value = validateAndTransform(
    doc,
    path,
    schema,
    initialLog,
    rootSchema,
  ) as T;

  // Call the callback once with initial value if requested.
  let cleanup: Cancel | undefined = callback(value);

  // Subscribe to the docs that are read (via logs), call callback on next change.
  if (!doc.runtime) {
    throw new Error("No runtime available for subscribe");
  }
  const cancel = doc.runtime.scheduler.subscribe((log) => {
    const newLog = {
      reads: [],
      writes: [],
    } satisfies ReactivityLog;

    if (isCancel(cleanup)) cleanup();
    const newValue = validateAndTransform(
      doc,
      path,
      schema,
      newLog,
      rootSchema,
    ) as T;
    // Copy reads to log _before_ calling the callback, as we're only interested
    // in dependencies for the initial get, not further cells the callback might
    // read. The callback is responsible for calling sink on those cells if it
    // wants to stay updated.
    log.reads.push(...newLog.reads);
    cleanup = callback(newValue);
  }, initialLog);

  return () => {
    cancel();
    if (isCancel(cleanup)) cleanup();
  };
}

/**
 * Check if value is a simple cell.
 *
 * @param {any} value - The value to check.
 * @returns {boolean}
 */
export function isCell(value: any): value is Cell<any> {
  return isRecord(value) && value[isCellMarker] === true;
}

const isCellMarker = Symbol("isCell");

/**
 * Type guard to check if a value is a Stream.
 * @param value - The value to check
 * @returns True if the value is a Stream
 */
export function isStream(value: any): value is Stream<any> {
  return isRecord(value) && value[isStreamMarker] === true;
}

const isStreamMarker = Symbol("isStream");

/**
 * Check if value is a cell link.
 *
 * @param {any} value - The value to check.
 * @returns {boolean}
 */
export function isCellLink(value: any): value is CellLink {
  return (
    isRecord(value) && isDoc(value.cell) && Array.isArray(value.path)
  );
}
