import { type ImmutableJSONValue, JSONSchemaObj } from "@commonfabric/api";
import { isRecord } from "@commonfabric/utils/types";
import { getLogger } from "@commonfabric/utils/logger";
import { deepEqual } from "@commonfabric/utils/deep-equal";
import { internSchema } from "@commonfabric/data-model/schema-hash";
import type { CellKind, JSONSchema } from "./builder/types.ts";
import { CycleTracker } from "./traverse.ts";
import { isArrayIndexPropertyName } from "@commonfabric/data-model/fabric-value";
import { toCompactDebugString } from "@commonfabric/data-model/value-debug";
import { rendererVDOMSchema, vnodeSchema } from "@commonfabric/runner/schemas";
import { decodeJsonPointer } from "./link-types.ts";
export { CFC_ATOM_TYPE, CFC_RUNTIME_SUBJECT, cfcAtom } from "./cfc/atoms.ts";

const logger = getLogger("cfc");
type IFCAtom = ImmutableJSONValue;

// Mapping from ref url to schema object
// Any $ref links in these must be self contained or absolute
const embeddedSchemas: Record<string, JSONSchema> = {
  "https://commonfabric.org/schemas/vdom.json": rendererVDOMSchema,
  "https://commonfabric.org/schemas/vnode.json": vnodeSchema,
};

// Class for handling cfc rules.
// The spec's confidentiality model is based on structured atoms.
export class ContextualFlowControl {
  static uniqueAtoms(atoms: Iterable<unknown>): IFCAtom[] {
    const unique: IFCAtom[] = [];
    for (const atom of atoms) {
      if (!unique.some((existing) => deepEqual(existing, atom))) {
        unique.push(atom as IFCAtom);
      }
    }
    return unique;
  }

  static addIfcAtoms(
    joined: Set<unknown>,
    atoms: readonly IFCAtom[] | undefined,
  ): void {
    if (!Array.isArray(atoms)) {
      return;
    }
    for (const atom of atoms) {
      joined.add(atom);
    }
  }

  /**
   * Collect any required confidentiality atoms required by the schema.
   * This could be made more conservative by combining the schema with the object
   * If our object lacks any of the fields that would add confidentiality,
   * we don't need to consider them.
   *
   * @param joined set to which we will add any confidentiality atoms
   * @param schema the schema with tags
   * @param fullSchema the full schema with any $defs needed
   * @param cycleTracker used to avoid reference cycles
   */
  static joinSchema(
    joined: Set<unknown>,
    schema: JSONSchema,
    fullSchema: JSONSchema = schema,
    cycleTracker: CycleTracker<JSONSchema> = new CycleTracker<JSONSchema>(true),
  ): Set<unknown> {
    if (typeof schema === "boolean") {
      return joined;
    }
    // A resolved schema is often unique, since it's generated by combining
    // other schema. `internSchema()` returns the canonical (identity-unique)
    // schema object, so structurally-equal schemas collapse to the same
    // reference — the cycle tracker can then dedup by identity. Also
    // correctly handles non-JSON-compatible `FabricValue`s (e.g.
    // `FabricEpochNsec`, `FabricBytes`, `FabricHash`) that may appear in
    // schema `default` fields; plain `JSON.stringify` would silently
    // mis-encode them.
    using t = cycleTracker.include(internSchema(schema));
    if (t === null) {
      // we've already joined this
      return joined;
    }
    if (schema.ifc) {
      ContextualFlowControl.addIfcAtoms(joined, schema.ifc.confidentiality);
    }
    if (schema.properties && typeof schema.properties === "object") {
      for (const value of Object.values(schema.properties)) {
        ContextualFlowControl.joinSchema(
          joined,
          value,
          fullSchema,
          cycleTracker,
        );
      }
    }
    if (
      schema.additionalProperties &&
      typeof schema.additionalProperties === "object"
    ) {
      ContextualFlowControl.joinSchema(
        joined,
        schema.additionalProperties,
        fullSchema,
        cycleTracker,
      );
    } else if (schema.items && typeof schema.items === "object") {
      // TODO(@ubik2): need to handle prefixItems -- also probably not else if here
      ContextualFlowControl.joinSchema(
        joined,
        schema.items,
        fullSchema,
        cycleTracker,
      );
    } else if (schema.$ref) {
      // Follow the references
      const resolvedSchema = ContextualFlowControl.resolveSchemaRefsOrThrow(
        schema,
        fullSchema,
      );
      if (schema.$ref in embeddedSchemas) {
        // Absolute $ref means we should reset our fullSchema
        fullSchema = resolvedSchema;
      }
      ContextualFlowControl.joinSchema(
        joined,
        resolvedSchema,
        fullSchema,
        cycleTracker,
      );
    }
    return joined;
  }

  // Get the joined confidentiality atoms from the schema.
  public lubSchema(
    schema: JSONSchema,
    extraConfidentiality?: Set<unknown>,
  ): IFCAtom[] | undefined {
    const confidentiality = (extraConfidentiality !== undefined)
      ? new Set<unknown>(extraConfidentiality)
      : new Set<unknown>();
    ContextualFlowControl.joinSchema(confidentiality, schema);

    return (confidentiality.size === 0) ? undefined : this.lub(confidentiality);
  }

  public lub(joined: Set<unknown>): IFCAtom[] {
    return ContextualFlowControl.uniqueAtoms(joined);
  }

  // Return a copy of the schema with joined confidentiality atoms.
  public schemaWithLub(
    schema: JSONSchema,
    confidentiality: readonly unknown[],
  ): JSONSchema {
    const joined = new Set<unknown>(confidentiality);
    if (isRecord(schema) && schema.ifc !== undefined) {
      ContextualFlowControl.addIfcAtoms(joined, schema.ifc.confidentiality);
    }
    // If we have no confidentiality, we can leave the schema
    if (joined.size === 0) {
      return schema;
    }
    // We don't really support "not" schemas, but it's the only good way we
    // have to attach ifc to a `false` schema.
    const schemaObj = ContextualFlowControl.toSchemaObj(schema);
    const restrictedSchema = {
      ...schemaObj,
      ifc: { ...schemaObj.ifc, confidentiality: this.lub(joined) },
    };
    return restrictedSchema;
  }

  /**
   * Convert a schema that may be undefined or boolean to an object version.
   *
   * @param schema optional schema to convert
   */
  static toSchemaObj(schema?: JSONSchema): JSONSchemaObj {
    return (schema === true || schema === undefined)
      ? {}
      : schema === false
      ? { not: true }
      : schema;
  }

  /**
   * Resolve a $ref in a schema, following other $ref links if needed.
   *
   * This doesn't currently handle $anchor tags or external documents
   * This will follow the $ref until the top level object is not a $ref.
   *
   * @param schemaObj an object containing the $ref, which may have properties
   *     that override those in the object pointed to by the $ref.
   * @param fullSchema Top level document for the schema which will be used
   *     to resolve the $ref. This should have the $defs.
   * @returns an updated JSONSchema, with a schema that points to the
   *     $ref's final target or undefined if the $ref could not be resolved.
   */
  static resolveSchemaRefs(
    schemaObj: JSONSchemaObj,
    fullSchema: JSONSchema = schemaObj,
  ): JSONSchema | undefined {
    // Track seen refs to avoid cycles
    const seenRefs = new Set<string>();
    while (true) {
      const { $ref, ...rest } = schemaObj;
      if ($ref === undefined) { // no more refs to resolve
        return schemaObj;
      } else if (seenRefs.has($ref)) {
        // Cycle -- equivalent to non-existent ref
        return undefined;
      }
      seenRefs.add($ref);
      const resolved = ContextualFlowControl.resolveSchemaRef(
        fullSchema,
        $ref,
      );
      if (resolved === undefined) { // Non-existent ref
        return undefined;
      } else if ($ref in embeddedSchemas) {
        // Absolute $ref means we should reset our fullSchema
        fullSchema = resolved;
      }
      // If we have other properties, we need to keep them as we resolve refs.
      // They will override any properties in those refs.
      if (Object.keys(rest).length > 0) {
        if (isRecord(resolved)) {
          // Merge our attributes with those in the ref
          // If we replaced the fullSchema, pull in those $defs instead
          schemaObj = {
            ...resolved,
            ...rest,
            ...(isRecord(fullSchema) && fullSchema.$defs &&
              { $defs: fullSchema.$defs }),
          } as JSONSchemaObj;
        } else {
          // Resolved to a boolean schema, so we can stop
          const schema = ContextualFlowControl.toSchemaObj(resolved);
          schemaObj = { ...schema, ...rest } as JSONSchemaObj;
        }
      } else if (typeof resolved === "boolean") {
        return resolved;
      } else {
        schemaObj = resolved;
      }
    }
  }

  // TODO(@ubik2): We may need to collect ifc labels as we walk the tree
  // This could be dome similarly to schemaAtPath, but that assumes
  // our cursor points at a schema, while we will walk objects like the
  // $defs that are not schema.
  // In the case where we point to a definition, this should already do
  // the right thing, since those are all at the top level. However, we
  // could have a reference to an anchor (not currently allowed), and
  // for those, if the User is secret, their Address should be too.
  /**
   * Resolve a $ref in a schema.
   * This doesn't currently handle $anchor tags or external documents
   *
   * If the schemaRef points to an object that is also a $ref, this will not
   * follow that link. Use resolveSchemaRefs for that behavior.
   *
   * @param fullSchema Top level document for the schema which will be used
   *     to resolve the $ref.
   * @param schemaRef the string value of the $ref
   * @returns an updated JSONSchema, with a schema that points to the
   *     $ref's target or undefined if the $ref could not be resolved.
   */
  static resolveSchemaRef(
    fullSchema: JSONSchema,
    schemaRef: string,
  ): JSONSchema | undefined {
    // Allow for some absolute schema refs
    if (schemaRef in embeddedSchemas) {
      return embeddedSchemas[schemaRef];
    }
    // We only support schemaRefs that are URI fragments
    if (!schemaRef.startsWith("#")) {
      logger.warn("cfc", () => ["Unsupported $ref in schema: ", schemaRef]);
      return undefined;
    }
    // URI fragment schemaRefs are JSONPointers, so split and unescape
    const pathToDef = decodeJsonPointer(schemaRef);
    // We don't support anchors yet (e.g. `"$ref": "#address"`)
    if (pathToDef[0] !== "#") {
      logger.warn(
        "cfc",
        () => ["Unsupported anchor $ref in schema: ", schemaRef],
      );
      return undefined;
    }
    let schemaCursor: unknown = fullSchema;
    // start at 1, since the 0 element is "#"
    for (let i = 1; i < pathToDef.length; i++) {
      if (!isRecord(schemaCursor) || !(pathToDef[i] in schemaCursor)) {
        logger.warn(
          "cfc",
          () => ["Unresolved $ref in schema: ", schemaRef, fullSchema],
        );
        return undefined;
      }
      schemaCursor = schemaCursor[pathToDef[i]];
    }
    // If our schema cursor is an object, carry the $defs in
    if (typeof schemaCursor === "object") {
      const schemaRefs = new Set<string>();
      this.findRefs(schemaCursor as JSONSchema, schemaRefs);
      // TODO(@ubik2): We could just carry in the $defs we need
      if (schemaRefs.size > 0) {
        schemaCursor = {
          ...schemaCursor,
          ...(isRecord(fullSchema) && fullSchema.$defs &&
            { $defs: fullSchema.$defs }),
        };
      }
    }
    return schemaCursor as JSONSchema;
  }

  /**
   * Traverse a schema finding any $ref links.
   *
   * This does not scan the $defs, so a $ref that points to a $defs entry that
   * then references another $defs entry would not have that second reference
   * included.
   *
   * @param schema
   * @param refSet
   */
  static findRefs(
    schema: JSONSchema,
    refSet: Set<string> = new Set<string>(),
  ): void {
    if (typeof schema === "boolean") {
      return;
    }
    if (schema.$ref !== undefined) {
      refSet.add(schema.$ref);
    }
    if (schema.type === "array") {
      if (schema.items !== undefined) {
        ContextualFlowControl.findRefs(schema.items, refSet);
      }
      if (schema.prefixItems != undefined) {
        for (const item of schema.prefixItems) {
          ContextualFlowControl.findRefs(item, refSet);
        }
      }
    } else if (schema.type === "object") {
      if (schema.additionalProperties !== undefined) {
        ContextualFlowControl.findRefs(schema.additionalProperties, refSet);
      }
      if (schema.properties !== undefined) {
        for (const [_key, propSchema] of Object.entries(schema.properties)) {
          ContextualFlowControl.findRefs(propSchema, refSet);
        }
      }
    }
    const optSchemas = [
      ...(schema.anyOf ? schema.anyOf : []),
      ...(schema.oneOf ? schema.oneOf : []),
      ...(schema.allOf ? schema.allOf : []),
    ];
    for (const optSchema of optSchemas) {
      ContextualFlowControl.findRefs(optSchema, refSet);
    }
  }

  static resolveSchemaRefsOrThrow(
    schemaObj: JSONSchemaObj,
    fullSchema: JSONSchema = schemaObj,
  ) {
    if (!isRecord(fullSchema)) {
      // We'd need a fullSchema to make this work
      // We don't need to do real cycle detection, since the path is limited
      throw new Error("Found $ref without fullSchema object");
    }
    const resolved = ContextualFlowControl.resolveSchemaRefs(
      schemaObj,
      fullSchema,
    );
    if (resolved === undefined) {
      const ref = "$ref" in schemaObj
        ? schemaObj.$ref
        : toCompactDebugString(schemaObj);
      throw new Error(
        `Failed to resolve $ref: ${ref}. ` +
          (typeof ref === "string" && ref.startsWith("http")
            ? `External $ref URLs must be registered in embeddedSchemas (packages/runner/src/cfc.ts). ` +
              `If you added a new native type to NATIVE_TYPE_SCHEMAS in ` +
              `packages/schema-generator/src/formatters/native-type-formatter.ts, ` +
              `add its schema to embeddedSchemas as well.`
            : `Schema: ${toCompactDebugString(schemaObj)}`),
      );
    }
    return resolved;
  }

  // This is a variant of schemaAtPath that allows for an undefined schema.
  // It will return the empty object instead of true and undefined instead of false.
  getSchemaAtPath(
    schema: JSONSchema | undefined,
    path: string[],
    extraConfidentiality?: Set<unknown>,
  ): JSONSchema | undefined {
    if (schema === undefined) {
      return undefined;
    }
    const result = this.schemaAtPath(schema, path, extraConfidentiality);
    return result === false ? undefined : result === true ? {} : result;
  }

  /**
   * This gets the schema at a specific path.
   * This is a leaky abstraction, since you can have changes in a parent object
   * that shape the potential values and types of child objects.
   *
   * For example, if you have anyOf USAddress, CanadaAddress and the USAddress
   * differentiated by country name, when you ask for the postalCode, the schema
   * if the parent portions were a USAddress is a a sequence of 5 numbers.
   * However if the parent portions were a CanadaAddress, the postalCode is a
   * sequence of 6 letters or numbers.
   *
   * You can't know how the schema will be narrowed without evaluating it
   * against a candidate object.
   *
   * Nonetheless, it's very convenient to have a schema without knowing, so we
   * provide this method and use it.
   *
   * The additionalPropertiesDefault lets you change the behavior when there is
   * an object with an empty properties map and no additional properties.
   * The JSON-Schema spec would default this to true, but we often want to
   * use it to exclude properties that we don't care about without failing.
   * We also allow you to provide a special string value, so the caller can detect
   * that this has happened.
   *
   * While we will handle $ref links as needed while getting to the schema,
   * the returned object will retain those $ref links.
   */
  schemaAtPath(
    schema: JSONSchema,
    path: readonly string[],
    extraConfidentiality?: Set<unknown>,
    defaultEmptyProperties: JSONSchema = true,
    defaultMissingProperty: JSONSchema = true,
  ): JSONSchema {
    // Take defs from schema if available
    const defs = isRecord(schema) && schema.$defs ? schema.$defs : undefined;
    return this.schemaAtPathInternal(
      schema,
      path,
      defs,
      extraConfidentiality,
      defaultEmptyProperties,
      defaultMissingProperty,
    );
  }

  private schemaAtPathInternal(
    schema: JSONSchema,
    path: readonly string[],
    defs: Record<string, JSONSchema> | undefined,
    extraConfidentiality: Set<unknown> | undefined,
    defaultEmptyProperties: JSONSchema,
    defaultMissingProperty: JSONSchema,
  ): JSONSchema {
    const joined = (extraConfidentiality !== undefined)
      ? new Set<unknown>(extraConfidentiality)
      : new Set<unknown>();
    let cursor = schema;
    for (
      const [index, part] of path.map((value, index) =>
        [index, value] as [number, string]
      )
    ) {
      // If the cursor is a $ref, get the target location
      if (isRecord(cursor) && "$ref" in cursor) {
        // Follow the reference
        cursor = ContextualFlowControl.resolveSchemaRefsOrThrow(
          cursor,
          { $defs: defs },
        );
        // Resolve schema refs can resolve to a fullSchema, in which case we
        // need to replace our defs.
        if (isRecord(cursor) && cursor.$defs) {
          defs = cursor.$defs;
        }
      }
      if (isRecord(cursor) && ("anyOf" in cursor || "oneOf" in cursor)) {
        const subSchemas = new Set<JSONSchema>();
        const options = (cursor.anyOf && cursor.oneOf)
          ? [...cursor.anyOf, ...cursor.oneOf]
          : cursor.anyOf ?? cursor.oneOf ?? [];
        for (const entry of options) {
          const optSchema = this.schemaAtPathInternal(
            entry,
            path.slice(index),
            defs,
            extraConfidentiality,
            defaultEmptyProperties,
            defaultMissingProperty,
          );
          if (typeof optSchema !== "boolean" && typeof optSchema !== "object") {
            return optSchema;
          }
          const subSchema = optSchema as JSONSchema | boolean;
          if (subSchema === false) {
            continue;
          } else if (ContextualFlowControl.isTrueSchema(subSchema)) {
            cursor = true;
            break;
          } else {
            // `internSchema()` returns the canonical (identity-unique)
            // schema object, so structurally-equal schemas collapse to
            // the same reference. That gives identity-based dedup via
            // `Set<JSONSchema>`, and correctly handles non-JSON-compatible
            // `FabricValue`s (e.g. `FabricEpochNsec`, `FabricBytes`,
            // `FabricHash`) that may appear in schema `default` fields.
            subSchemas.add(internSchema(subSchema as JSONSchema));
          }
        }
        // Only update cursor from subSchemas if the isTrueSchema branch
        // didn't already set cursor = true and break out of the loop.
        if (cursor !== true) {
          const subSchemaArr = [...subSchemas];
          if (subSchemaArr.length === 0) {
            cursor = false;
          } else if (subSchemaArr.length === 1) {
            cursor = subSchemaArr[0];
          } else {
            cursor = { "anyOf": subSchemaArr };
          }
        }
        break;
      }
      if (typeof cursor === "boolean") {
        break;
      } else if (ContextualFlowControl.isTrueSchema(cursor)) {
        // wildcard schema -- equivalent to true, but we can add ifc tags
        break;
      } else if (cursor.type === "object") {
        if (cursor.ifc !== undefined) {
          ContextualFlowControl.addIfcAtoms(
            joined,
            cursor.ifc.confidentiality,
          );
        }
        if (cursor.properties && part in cursor.properties) {
          const cursorObj = cursor.properties as Record<string, JSONSchema>;
          cursor = cursorObj[part];
          if (typeof cursor === "boolean") {
            break;
          } else {
            if (cursor.ifc !== undefined) {
              ContextualFlowControl.addIfcAtoms(
                joined,
                cursor.ifc.confidentiality,
              );
            }
          }
        } else if (cursor.additionalProperties !== undefined) {
          cursor = cursor.additionalProperties;
        } else if (
          cursor.properties && Object.keys(cursor.properties).length === 0
        ) {
          // We'll often ignore, but validate in this case
          cursor = defaultEmptyProperties;
        } else if (cursor.properties) {
          // We'll generally include these, but sometimes we don't
          cursor = defaultMissingProperty;
        } else { // no additionalProperties field is the same as having one that is true
          cursor = true;
        }
      } else if (cursor.type === "array") {
        if (isArrayIndexPropertyName(part)) {
          const index = Number(part);
          if (cursor.prefixItems && index < cursor.prefixItems.length) {
            cursor = cursor.prefixItems[index];
          } else {
            cursor = cursor.items ?? true;
          }
        } else {
          return false;
        }
      } else if (
        cursor.type === "unknown" ||
        Array.isArray(cursor.type) && cursor.type.includes("unknown")
      ) {
        // we can descend into unknown, but we just get more unknown
        cursor = { type: "unknown", ...(cursor.ifc && { ifc: cursor.ifc }) };
      } else {
        // we can only descend into objects and arrays or unknown
        return false;
      }
      if (isRecord(cursor) && cursor.$defs) {
        defs = cursor.$defs;
      }
    }
    if (isRecord(cursor) && cursor.ifc !== undefined) {
      ContextualFlowControl.addIfcAtoms(joined, cursor.ifc.confidentiality);
    }
    if (typeof cursor === "boolean") {
      if (!cursor) {
        return false; // no need to attach tags -- we'll never match
      } else if (joined.size === 0) {
        return true; // no ifc tags -- can just return true
      }
      cursor = {}; // change to use the empty object schema, so we can attach ifc.
    }
    // If we've encountered any confidentiality atoms while walking down the
    // schema, we need to add them to the returned object.
    const ifc = (joined.size !== 0)
      ? { ...cursor.ifc, confidentiality: this.lub(joined) }
      : cursor.ifc;
    // Merge any ifc and defs
    return { ...cursor, ...(ifc && { ifc }), ...(defs && { $defs: defs }) };
  }

  // Check to see if the specified schema is one of the special values meaning
  // it should always validate.
  static isTrueSchema(schema: JSONSchema): boolean {
    if (schema === true) {
      return true;
    }
    return isRecord(schema) &&
      Object.keys(schema).every((k) =>
        this.isInternalSchemaKey(k) || k === "default" || k === "$defs"
      );
  }

  // We don't need to check ID and ID_FIELD, since they won't be included
  // in Object.keys return values.
  static isInternalSchemaKey(key: string): boolean {
    return key === "ifc" || key === "asCell" || key === "asStream";
  }

  static isFalseSchema(schema: JSONSchema): boolean {
    return schema === false ||
      (isRecord(schema) && "not" in schema &&
        this.isTrueSchema(schema["not"]!));
  }

  // Utility function to handle the legacy asCell and asStream tags, as well
  // as the modern asCell array tag.
  static getAsCellValues(schema: JSONSchema | undefined): readonly CellKind[] {
    // Support both modern and legacy versions
    if (isRecord(schema)) {
      if (Array.isArray(schema.asCell)) {
        return schema.asCell;
      } else if (schema.asCell === true) {
        return ["cell"];
      } else if (schema.asStream === true) {
        return ["stream"];
      }
    }
    return [];
  }
}
