// Relative weights from successful CI runs. Only tests whose cost materially
// affects placement need an entry; selectors use a default for the long tail.

/**
 * Relative weights for the `agents-host` test files. The debug-view suite
 * dominates the package, which is why it spans several files; the rest are
 * cheap enough that the default covers them.
 */
export const AGENTS_HOST_TEST_WEIGHTS: Readonly<Record<string, number>> = {
  "test/debug_view_pattern_test.ts": 40,
  "test/debug_view_deployment_test.ts": 33,
  "test/debug_view_replacement_test.ts": 16,
  "test/cli_test.ts": 3.3,
  "test/start_test.ts": 3.1,
  "test/host_test.ts": 2.9,
  "test/config_test.ts": 2.5,
};

export const RUNNER_TEST_WEIGHTS: Readonly<Record<string, number>> = {
  "source-reconciler.test.ts": 20.6,
  "profile-owner-cfc.test.ts": 19.0,
  "engine-ses.test.ts": 14.3,
  "fabric-imports-engine.test.ts": 13.7,
  "pattern-update-argument-validation.test.ts": 12.8,
  "engine-evaluate-record-graph.test.ts": 12.6,
  "home-add-favorite.test.ts": 11.8,
  "to-encodable-form.test.ts": 11.2,
  "esm-cell-cache-integration.test.ts": 11.1,
  "list-resume-container-defer.test.ts": 9.9,
  "load-by-identity.test.ts": 9.6,
  "esm-engine.test.ts": 8.8,
  "cfc-nonexported-binding-identity.test.ts": 8.7,
  "profile-space-identity-collision-did.test.ts": 8.1,
  "list-resume-preserve.test.ts": 7.7,
  "profile-space-identity-collision-users.test.ts": 7.7,
  "pattern-coverage.test.ts": 7.4,
  "profile-space-identity-collision-same-user.test.ts": 7.1,
  "content-addressed-identity.test.ts": 6.4,
  "module-identity-engine.test.ts": 6.2,
  "traverse-replay.test.ts": 6.1,
  "cfc-additive-default-preserves-old-doc.test.ts": 5.8,
  "engine-compile-record-graph.test.ts": 5.7,
  "cross-space-value-read.test.ts": 5.4,
  "profile-home-verified-identities.test.ts": 5.4,
  "profile-create-real-card-add.test.ts": 5.3,
  "security.test.ts": 5.2,
  "fabric-imports-pattern-manager.test.ts": 5.2,
  "content-addressed-identity-adversarial.test.ts": 5.1,
  "cell-cache.test.ts": 5.0,
  "favorites-row-stored-shape.test.ts": 4.8,
  "module.test.ts": 4.8,
  "list-fresh-init.test.ts": 4.6,
  "twin-lineage-provenance.test.ts": 4.6,
  "resume-owned-cells-skip-log.test.ts": 4.5,
  "declared-result-e2e.test.ts": 4.2,
  "module-byte-cache.test.ts": 4.2,
  "nested-piece-setup-repair.test.ts": 4.0,
  "pattern-manager.test.ts": 4.0,
  "list-resume-input-settle.test.ts": 3.9,
  "list-builtin-edge-paths.test.ts": 3.9,
  "mergeable-append-multispace-conflict.test.ts": 3.8,
  "pattern-swap-link-argument.test.ts": 3.8,
  "fabric-primitive-pattern-reactivity.test.ts": 3.7,
  "profile-home-bio.test.ts": 3.7,
  "fabric-imports-snapshot.test.ts": 3.5,
  "stream-event-fabric-primitives.test.ts": 3.5,
  "resume-owned-cells.test.ts": 3.4,
  "artifact-index-pinning.test.ts": 3.4,
  "profile-home-pin-piece.test.ts": 3.3,
  "pattern-source-path.test.ts": 3.2,
  "pattern-ref-boundary.test.ts": 3.2,
  "stack-trace-patterns.test.ts": 3.2,
  "map-op-by-identity.test.ts": 3.1,
  "by-identity-handler-exec.test.ts": 3.1,
  "runtime.test.ts": 3.1,
  "cfc-policy-of-label.test.ts": 3.0,
  "stack-trace.test.ts": 3.0,
};

export const PIECE_TEST_WEIGHTS: Readonly<Record<string, number>> = {
  "test/check-update-default-pattern.test.ts": 9.1,
  "test/default-app-golden-replay.test.ts": 1.0,
  "test/default-pattern-persistence.test.ts": 0.6,
  "test/ensure-default-pattern.test.ts": 0.7,
  "test/home-golden-replay.test.ts": 0.5,
  "test/legacy-envelope-default-pattern.test.ts": 0.7,
  "test/pattern-compatibility-check.test.ts": 1.8,
  "test/piece-origin.test.ts": 0.8,
  "test/piece-source-lifecycle.test.ts": 5.3,
  "test/pull-materialization.test.ts": 6.7,
  "test/setsrc-cold-argument.test.ts": 0.6,
  "test/setsrc-module-delegation.test.ts": 1.3,
  "test/setsrc-retained-capability-link.test.ts": 0.6,
  "test/state-continuity.test.ts": 1.9,
};

export const TASK_TEST_WEIGHTS: Readonly<Record<string, number>> = {
  "check-skill-facts.test.ts": 0.8,
  "check-unused-deps.test.ts": 1.3,
  "ci-check-lib.test.ts": 1.8,
  "email-pattern-launcher-types.test.ts": 2.6,
  "pattern-vintage-run.test.ts": 15.8,
  "vintage-adopt.test.ts": 3.9,
  "write-coverage-lcov.test.ts": 3.1,
};

// Package weights model total CPU work. Each workspace job runs several
// package tasks concurrently, so equal total work keeps their worker queues
// close even when individual package durations differ.
export const WORKSPACE_TEST_WEIGHTS: Readonly<Record<string, number>> = {
  api: 2.3,
  "connectors/agents/host (1/3)": 40,
  "connectors/agents/host (2/3)": 33,
  "connectors/agents/host (3/3)": 16,
  "background-piece-service": 7.2,
  "cf-harness": 29.9,
  "cli (1/10)": 50.5,
  "cli (2/10)": 71,
  "cli (3/10)": 37,
  "cli (4/10)": 31,
  "cli (5/10)": 18.5,
  "cli (6/10)": 24,
  "cli (7/10)": 46,
  "cli (8/10)": 39,
  "cli (9/10)": 25,
  "cli (10/10)": 24.5,
  "content-hash": 3.6,
  dashboard: 14.8,
  "data-model": 9.3,
  "deno-web-test": 17.9,
  felt: 1.8,
  fuse: 12.9,
  "generated-patterns": 1,
  "home-schemas": 1,
  html: 16.3,
  identity: 9.6,
  "iframe-sandbox": 18.3,
  integration: 12.2,
  "js-compiler": 14.6,
  leb128: 1.4,
  "lib-shell": 13.7,
  llm: 1,
  memory: 49.8,
  patterns: 6.2,
  "patterns/auth": 1,
  "piece (1/3)": 60,
  "piece (2/3)": 60,
  "piece (3/3)": 60,
  "pure-json": 2.4,
  "runtime-client": 6,
  "schema-generator": 58.4,
  scripts: 1,
  shell: 16.4,
  "spec-model": 1.7,
  "state-inspector": 12.2,
  static: 8.9,
  "tasks (1/3)": 35,
  "tasks (2/3)": 25,
  "tasks (3/3)": 25,
  "test-support": 2.2,
  toolshed: 36.2,
  "ts-transformers": 58.2,
  ui: 31.4,
  utils: 19.6,
};
