/// <cts-enable />
/**
 * Multi-user test for generated-art auto-persistence.
 *
 * art-sync.test.tsx proves the host path end-to-end in one runtime, but a
 * single identity cannot witness the property the feature exists for: the
 * persisted image must be readable by a DIFFERENT user. The host's fetch
 * result cells are user-scoped (only the host's runtime can read the
 * generated bytes), so the trigger-driven `setOptionImage` send into the
 * space-scoped option element is the only reason Bob sees any image at all.
 * This runs ONE shared poll across two worker-isolated runtimes:
 * - Alice (host) adds an option; her runtime generates via the mocked
 *   /api/ai/img endpoint (the multi-user worker honors `fetchMocks`), the
 *   hidden auto-persist trigger img renders, and — the workers having no
 *   real DOM — her test fires its `load` by sending into the trigger's
 *   onLoad stream (browser event and send reach the identical handler),
 * - Bob joins and, from his own runtime, reads the exact persisted data URL
 *   off the shared option — never having generated anything himself
 *   (shouldGenerate gates on isAdmin).
 *
 * Assertions retry with settling until the step timeout, which is what
 * drives Alice's in-flight mocked fetch to completion before she fires the
 * trigger. Cross-runtime reads use INLINE literal accesses — see
 * multi-user.test.tsx.
 */
import { action, computed, multiUserTest, pattern, UI } from "commonfabric";
import LunchPoll, { type CozyPollOutput } from "./main.tsx";

// 1×1 transparent PNG; the persisted value is its exact data URL (fetch bytes
// → base64 re-encode is an identity round-trip; see art-sync.test.tsx).
const TINY_PNG_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==";

export const fetchMocks = [
  {
    urlIncludes: "/api/ai/img",
    contentType: "image/png",
    base64Body: TINY_PNG_BASE64,
  },
];

const EXPECTED_DATA_URL =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==";

const isRecord = (value: unknown): value is Record<PropertyKey, unknown> =>
  typeof value === "object" && value !== null;

const readValue = (value: unknown): unknown => {
  if (!isRecord(value) || typeof value.get !== "function") {
    return value;
  }
  return (value.get as () => unknown)();
};

const propsOf = (node: unknown): Record<PropertyKey, unknown> | undefined => {
  const value = readValue(node);
  if (!isRecord(value)) return undefined;
  const props = readValue(value.props);
  return isRecord(props) ? props : undefined;
};

const childrenArray = (children: unknown): unknown[] => {
  const value = readValue(children);
  if (Array.isArray(value)) return value;
  return value === undefined || value === null || typeof value === "boolean"
    ? []
    : [value];
};

const childNodes = (node: unknown): unknown[] => {
  const value = readValue(node);
  if (Array.isArray(value)) return value;
  if (!isRecord(value)) return [];
  const ui = value[UI];
  return [
    ...(ui === undefined || ui === value ? [] : [ui]),
    ...childrenArray(value.children),
  ];
};

const findNodeByProp = (
  root: unknown,
  prop: string,
  expected: unknown,
): unknown | undefined => {
  const value = readValue(root);
  const props = propsOf(value);
  if (props && readValue(props[prop]) === expected) return value;
  return childNodes(value)
    .map((child) => findNodeByProp(child, prop, expected))
    .find((child) => child !== undefined);
};

const findTriggerIn = (root: unknown, optionId: unknown): unknown =>
  findNodeByProp(root, "data-art-persist-trigger", optionId);

interface Setup {
  poll: CozyPollOutput;
}

export const setup = pattern(() => ({
  poll: LunchPoll({}),
}));

export const alice = pattern<{ setup: Setup }>(({ setup }) => {
  const poll = setup.poll;

  const action_join = action(() => {
    poll.joinAs.send({ name: "Alice" });
  });
  const action_add_sushi = action(() => {
    poll.addOption.send({ title: "Sushi Palace" });
  });

  const assert_option_added = computed(() =>
    (poll.options ?? []).length === 1 &&
    poll.options?.[0]?.title === "Sushi Palace"
  );

  // The assertion's settle-retry loop drives the mocked generation fetch;
  // once the bytes land the hidden trigger img renders with a wired onLoad.
  const assert_trigger_renders = computed(() =>
    findTriggerIn(poll[UI], readValue(poll.options?.[0]?.id)) !== undefined
  );

  // No real DOM in the worker — fire the trigger's `load` via its stream.
  const action_fire_trigger_load = action(() => {
    const trigger = findTriggerIn(poll[UI], readValue(poll.options?.[0]?.id));
    const onLoad = propsOf(trigger)?.onLoad;
    if (typeof onLoad === "object" && onLoad !== null && "send" in onLoad) {
      (onLoad as { send: (event: Record<string, never>) => void }).send({});
    }
  });

  const assert_art_persisted = computed(() =>
    poll.options?.[0]?.imageUrl === EXPECTED_DATA_URL
  );

  return {
    tests: [
      { action: action_join },
      { action: action_add_sushi },
      { assertion: assert_option_added },
      { assertion: assert_trigger_renders },
      { action: action_fire_trigger_load },
      { assertion: assert_art_persisted },
      { label: "alice-art-stored" },
    ],
  };
});

export const bob = pattern<{ setup: Setup }>(({ setup }) => {
  const poll = setup.poll;

  const action_join = action(() => {
    poll.joinAs.send({ name: "Bob" });
  });

  // The property under test: a non-host runtime reads the host's persisted
  // data URL off the shared option element. Bob's own card never generated
  // (he is not admin), so this value can only have come through the
  // trigger-driven persist.
  const assert_sees_persisted_art = computed(() =>
    poll.options?.[0]?.title === "Sushi Palace" &&
    poll.options?.[0]?.imageUrl === EXPECTED_DATA_URL &&
    poll.isAdmin === false
  );

  return {
    tests: [
      { await: "alice-art-stored" },
      { action: action_join },
      { assertion: assert_sees_persisted_art },
    ],
  };
});

export default multiUserTest({ setup, participants: { alice, bob } });
