packages:
  - "common-charm"
  - "common-builder"
  - "common-runner"
  - "llm-client"
  - "common-ui"
  - "common-identity"
  - "common-iframe-sandbox"
  - "common-os-ui"
  - "common-html"
  - "common-memory"
  - "jumble"
