// Generated by packages/static/scripts/generate-cfc-types.ts. Do not edit by hand.
//
// Declaration-only mirror of the public `commonfabric/cfc` authoring surface
// defined in packages/api/cfc-authoring.ts. The in-memory pattern compiler loads this
// file as the type module for `commonfabric/cfc`, so it stays
// declaration-only and must not emit runtime JavaScript.
//
// To regenerate after changing the authoring surface, run (from
// packages/static):
//   deno task gen-cfc-types
// To verify it is up to date, run:
//   deno task check-cfc-types

export type Cfc<T, Meta> = T & {
  readonly __ct_cfc__?: Meta;
};
export type CfcJsonValue =
  | null
  | boolean
  | number
  | string
  | CfcJsonArray
  | CfcAtomObject;
export interface CfcJsonArray extends ReadonlyArray<CfcJsonValue> {
}
export interface CfcAtomObject extends Readonly<Record<string, CfcJsonValue>> {
}
export type CfcAtom = CfcJsonValue;
export declare const CFC_ATOM_TYPE: {
  readonly BoundaryContext: "https://commonfabric.org/cfc/atom/BoundaryContext";
  readonly Builtin: "https://commonfabric.org/cfc/atom/Builtin";
  readonly Caveat: "https://commonfabric.org/cfc/atom/Caveat";
  readonly CaveatAssessment:
    "https://commonfabric.org/cfc/atom/CaveatAssessment";
  readonly CaveatScreened: "https://commonfabric.org/cfc/atom/CaveatScreened";
  readonly Concept: "https://commonfabric.org/cfc/atom/Concept";
  readonly DisclaimerAttached:
    "https://commonfabric.org/cfc/atom/DisclaimerAttached";
  readonly DisclosureAcknowledged:
    "https://commonfabric.org/cfc/atom/DisclosureAcknowledged";
  readonly DisclosureRendered:
    "https://commonfabric.org/cfc/atom/DisclosureRendered";
  readonly Expires: "https://commonfabric.org/cfc/atom/Expires";
  readonly ExternalIngest: "https://commonfabric.org/cfc/atom/ExternalIngest";
  readonly HasRole: "https://commonfabric.org/cfc/atom/HasRole";
  readonly InjectionSafe: "https://commonfabric.org/cfc/atom/InjectionSafe";
  readonly LinkReference: "https://commonfabric.org/cfc/atom/LinkReference";
  readonly LlmDerived: "https://commonfabric.org/cfc/atom/LlmDerived";
  readonly Origin: "https://commonfabric.org/cfc/atom/Origin";
  readonly PolicyCertified: "https://commonfabric.org/cfc/atom/PolicyCertified";
  readonly PromptSlotBound: "https://commonfabric.org/cfc/atom/PromptSlotBound";
  readonly PromptSlotInfluence:
    "https://commonfabric.org/cfc/atom/PromptSlotInfluence";
  readonly Resource: "https://commonfabric.org/cfc/atom/Resource";
  readonly Space: "https://commonfabric.org/cfc/atom/Space";
  readonly TransformedBy: "https://commonfabric.org/cfc/atom/TransformedBy";
  readonly User: "https://commonfabric.org/cfc/atom/User";
  readonly UserSurfaceInput:
    "https://commonfabric.org/cfc/atom/UserSurfaceInput";
};
export declare const CFC_RUNTIME_SUBJECT = "did:web:commonfabric.org#runtime";
export declare const CFC_CONCEPT_KIND: {
  readonly PromptInfluence:
    "https://commonfabric.org/cfc/concepts/prompt-influence";
  readonly PromptInjectionRiskIngressScreened:
    "https://commonfabric.org/cfc/concepts/prompt-injection-risk-ingress-screened";
  readonly PromptInjectionRiskUnscreened:
    "https://commonfabric.org/cfc/concepts/prompt-injection-risk-unscreened";
  readonly PromptInjectionRiskValueScreened:
    "https://commonfabric.org/cfc/concepts/prompt-injection-risk-value-screened";
};
export declare const CFC_FUSE_ATOM_CLASS: {
  readonly ProjectionMetadataIncomplete:
    "CommonFabricFuseProjectionMetadataIncomplete";
  readonly SymlinkTarget: "CommonFabricFuseSymlinkTarget";
  readonly TopologyObservation: "FilesystemTopologyObservation";
};
export type CfcResourceAtom = CfcAtomObject & {
  readonly type: typeof CFC_ATOM_TYPE.Resource;
  readonly class: string;
  readonly subject: string;
  readonly scope?: CfcAtom;
};
export type CfcCaveatAtom = CfcAtomObject & {
  readonly type: typeof CFC_ATOM_TYPE.Caveat;
  readonly kind: string;
  readonly source: CfcAtom;
  readonly by?: CfcAtom;
};
export type CfcBuiltinAtom = CfcAtomObject & {
  readonly type: typeof CFC_ATOM_TYPE.Builtin;
  readonly name: string;
};
export type CfcInjectionSafeAtom = CfcAtomObject & {
  readonly type: typeof CFC_ATOM_TYPE.InjectionSafe;
};
export type CfcUserSurfaceInputAtom = CfcAtomObject & {
  readonly type: typeof CFC_ATOM_TYPE.UserSurfaceInput;
  readonly user: string;
  readonly surface: string;
  readonly valueDigest: string;
};
type CfcLlmDerivedAtom = CfcAtomObject & {
  readonly type: typeof CFC_ATOM_TYPE.LlmDerived;
  readonly model?: string;
};
export type CfcExternalIngestAtom = CfcAtomObject & {
  readonly type: typeof CFC_ATOM_TYPE.ExternalIngest;
  readonly channel: string;
  readonly audience: string;
  readonly receivedAt: string;
  readonly valueDigest: string;
};
export type CfcUserAtom = CfcAtomObject & {
  readonly type: typeof CFC_ATOM_TYPE.User;
  readonly subject: string;
};
export type CfcSpaceAtom = CfcAtomObject & {
  readonly type: typeof CFC_ATOM_TYPE.Space;
  readonly id: string;
};
export type CfcExpiresAtom = CfcAtomObject & {
  readonly type: typeof CFC_ATOM_TYPE.Expires;
  readonly timestamp: number;
};
export type CfcHasRoleAtom = CfcAtomObject & {
  readonly type: typeof CFC_ATOM_TYPE.HasRole;
  readonly principal: string;
  readonly space: string;
  readonly role: "owner" | "writer" | "reader";
};
export type CfcBoundaryContextAtom = CfcAtomObject & {
  readonly type: typeof CFC_ATOM_TYPE.BoundaryContext;
  readonly key: string;
  readonly value?: string;
  readonly ref?: CfcAtom;
};
export type CfcCaveatScreenedAtom = CfcAtomObject & {
  readonly type: typeof CFC_ATOM_TYPE.CaveatScreened;
  readonly kind: string;
  readonly source: CfcAtom;
  readonly stage: string;
  readonly detector: CfcAtom;
  readonly verdict: string;
  readonly valueRef?: CfcAtom;
  readonly profileHash?: string;
  readonly screenedAt?: number;
};
export type CfcDisclosureRenderedAtom = CfcAtomObject & {
  readonly type: typeof CFC_ATOM_TYPE.DisclosureRendered;
  readonly kind: string;
  readonly source: CfcAtom;
  readonly sink: string;
  readonly renderRef: CfcAtom;
  readonly snapshotDigest: string;
  readonly user?: string;
};
export type CfcDisclosureAcknowledgedAtom = CfcAtomObject & {
  readonly type: typeof CFC_ATOM_TYPE.DisclosureAcknowledged;
  readonly user: string;
  readonly kind: string;
  readonly source: CfcAtom;
  readonly renderRef: CfcAtom;
  readonly snapshotDigest: string;
  readonly sink?: string;
};
export type CfcDisclaimerAttachedAtom = CfcAtomObject & {
  readonly type: typeof CFC_ATOM_TYPE.DisclaimerAttached;
  readonly sink: string;
  readonly kind: string;
  readonly source: CfcAtom;
  readonly disclaimerDigest: string;
  readonly formatter?: CfcAtom;
};
export type CfcConceptAtom = CfcAtomObject & {
  readonly type: typeof CFC_ATOM_TYPE.Concept;
  readonly uri: string;
};
export type CfcCaveatAssessmentAtom = CfcAtomObject & {
  readonly type: typeof CFC_ATOM_TYPE.CaveatAssessment;
  readonly kind: string;
  readonly source: CfcAtom;
  readonly assessor: CfcAtom;
  readonly evidenceDigest: string;
  readonly result: "supported" | "rejected";
  readonly sink?: string;
  readonly intentId?: CfcAtom;
  readonly purpose?: string;
  readonly assessedAt?: number;
};
export type CfcPromptSlotBoundAtom<
  Source extends CfcAtom = CfcAtom,
  Role extends string = string,
> = CfcAtomObject & {
  readonly type: typeof CFC_ATOM_TYPE.PromptSlotBound;
  readonly source: Source;
  readonly role: Role;
  readonly kernelName: string;
  readonly surface: string;
  readonly subject?: string;
  readonly renderRef?: CfcAtom;
  readonly eventId?: string;
  readonly valueDigest?: string;
  readonly slotDigest?: string;
  readonly snapshotDigest?: string;
  readonly targetPath?: string;
};
export type CfcPromptSlotRunManifest = CfcAtomObject & {
  readonly source?: string;
  readonly wishId?: string;
  readonly dispatchClass?: string;
};
export type CfcPromptSlotInfluenceAtom<Role extends string = string> =
  & CfcAtomObject
  & {
    readonly type: typeof CFC_ATOM_TYPE.PromptSlotInfluence;
    readonly version: 1;
    readonly role: Role;
    readonly kernelName: string;
    readonly surface: string;
    readonly subject?: string;
    readonly eventId?: string;
    readonly valueDigest?: string;
    readonly slotDigest?: string;
    readonly snapshotDigest?: string;
    readonly targetPath?: string;
    readonly runManifest?: CfcPromptSlotRunManifest;
  };
export declare const cfcAtom: {
  readonly resource: (
    className: string,
    subject?: string,
    scope?: CfcAtom,
  ) => CfcResourceAtom;
  readonly caveat: (
    kind: string,
    source: CfcAtom,
    by?: CfcAtom,
  ) => CfcCaveatAtom;
  readonly builtin: (name: string) => CfcBuiltinAtom;
  readonly injectionSafe: () => CfcInjectionSafeAtom;
  readonly llmDerived: (model?: string) => CfcLlmDerivedAtom;
  readonly userSurfaceInput: (
    user: string,
    surface: string,
    valueDigest: string,
  ) => CfcUserSurfaceInputAtom;
  readonly externalIngest: (
    channel: string,
    audience: string,
    receivedAt: string,
    valueDigest: string,
  ) => CfcExternalIngestAtom;
  readonly promptSlotBound: <Source extends CfcAtom, Role extends string>(
    source: Source,
    role: Role,
    kernelName: string,
    subject: string,
    surface: string,
    valueDigest: string,
  ) => CfcPromptSlotBoundAtom<Source, Role>;
  readonly user: (subject: string) => CfcUserAtom;
  readonly space: (id: string) => CfcSpaceAtom;
  readonly expires: (timestamp: number) => CfcExpiresAtom;
  readonly hasRole: (
    principal: string,
    space: string,
    role: "owner" | "writer" | "reader",
  ) => CfcHasRoleAtom;
  readonly boundaryContext: (
    key: string,
    value?: string,
    ref?: CfcAtom,
  ) => CfcBoundaryContextAtom;
  readonly caveatScreened: (fields: {
    kind: string;
    source: CfcAtom;
    stage: string;
    detector: CfcAtom;
    verdict: string;
    valueRef?: CfcAtom;
    profileHash?: string;
    screenedAt?: number;
  }) => CfcCaveatScreenedAtom;
  readonly disclosureRendered: (fields: {
    kind: string;
    source: CfcAtom;
    sink: string;
    renderRef: CfcAtom;
    snapshotDigest: string;
    user?: string;
  }) => CfcDisclosureRenderedAtom;
  readonly disclosureAcknowledged: (fields: {
    user: string;
    kind: string;
    source: CfcAtom;
    renderRef: CfcAtom;
    snapshotDigest: string;
    sink?: string;
  }) => CfcDisclosureAcknowledgedAtom;
  readonly disclaimerAttached: (fields: {
    sink: string;
    kind: string;
    source: CfcAtom;
    disclaimerDigest: string;
    formatter?: CfcAtom;
  }) => CfcDisclaimerAttachedAtom;
  readonly caveatAssessment: (fields: {
    kind: string;
    source: CfcAtom;
    assessor: CfcAtom;
    evidenceDigest: string;
    result: "supported" | "rejected";
    sink?: string;
    intentId?: CfcAtom;
    purpose?: string;
    assessedAt?: number;
  }) => CfcCaveatAssessmentAtom;
  readonly concept: (uri: string) => CfcConceptAtom;
};
export declare const CFC_CANONICAL_ALIAS_NAMES: readonly [
  "Cfc",
  "Confidential",
  "Integrity",
  "AddIntegrity",
  "RepresentsCurrentUser",
  "AuthoredByCurrentUser",
  "RequiresIntegrity",
  "MaxConfidentiality",
  "OpaqueInput",
  "WriteAuthorizedBy",
  "TrustedActionWriteWithIntegrity",
  "TrustedActionWrite",
  "TrustedActionUiContract",
  "ExactCopy",
  "ProjectionPath",
  "ProjectionOf",
  "Projection",
  "LengthPreservedFrom",
  "FilteredFrom",
  "SubsetOf",
  "PermutationOf",
];
export type CfcCanonicalAliasName = typeof CFC_CANONICAL_ALIAS_NAMES[number];
export type Ref<Root, Path extends readonly string[]> = {
  readonly __ct_ref_root__?: Root;
  readonly __ct_ref_path__?: Path;
};
export type PathValue<Root, Path extends readonly string[]> = unknown;
export type RefValue<SourceRef> = unknown;
type EscapePointerSegment<Segment extends string> = Segment extends
  `${infer Head}~${infer Tail}` ? `${Head}~0${EscapePointerSegment<Tail>}`
  : Segment extends `${infer Head}/${infer Tail}`
    ? `${Head}~1${EscapePointerSegment<Tail>}`
  : Segment;
type JoinPointerPath<Path extends readonly string[]> = Path extends readonly []
  ? ""
  : Path extends readonly [
    infer First extends string,
    ...infer Rest extends readonly string[],
  ]
    ? `${EscapePointerSegment<First>}${Rest extends readonly [] ? ""
      : `/${JoinPointerPath<Rest>}`}`
  : never;
type CanonicalPointer<Path extends readonly string[]> = Path extends readonly []
  ? "/"
  : `/${JoinPointerPath<Path>}`;
export type Confidential<T, X extends readonly unknown[]> = Cfc<T, {
  confidentiality: X;
}>;
export type Integrity<T, X extends readonly unknown[]> = Cfc<T, {
  integrity: X;
}>;
export type AddIntegrity<T, X extends readonly unknown[]> = Cfc<T, {
  addIntegrity: X;
}>;
export type RepresentsCurrentUser<T> = Cfc<T, {
  addIntegrity: readonly [
    {
      readonly kind: "represents-principal";
      readonly subject: {
        readonly __ctCurrentPrincipal: true;
      };
    },
  ];
}>;
export type AuthoredByCurrentUser<T> = Cfc<T, {
  addIntegrity: readonly [
    {
      readonly kind: "authored-by";
      readonly subject: {
        readonly __ctCurrentPrincipal: true;
      };
    },
  ];
}>;
export type RequiresIntegrity<T, X extends readonly unknown[]> = Cfc<T, {
  requiredIntegrity: X;
}>;
export type MaxConfidentiality<T, X extends readonly unknown[]> = Cfc<T, {
  maxConfidentiality: X;
}>;
export type ExactCopy<T, P extends readonly string[]> = Cfc<T, {
  exactCopyOf: P;
}>;
export type LengthPreservedFrom<T, P extends readonly string[]> = Cfc<T, {
  collection: {
    sourceCollection: P;
    lengthPreserved: true;
  };
}>;
export type FilteredFrom<T, P extends readonly string[]> = Cfc<T, {
  collection: {
    filteredFrom: P;
  };
}>;
export type SubsetOf<T, P extends readonly string[]> = Cfc<T, {
  collection: {
    subsetOf: P;
  };
}>;
export type PermutationOf<T, P extends readonly string[]> = Cfc<T, {
  collection: {
    permutationOf: P;
  };
}>;
export type OpaqueInput<
  T,
  Spec extends true | {
    schema?: unknown;
    allowPassThrough?: boolean;
  } = true,
> = Cfc<T, {
  opaque: Spec;
}>;
export type ProjectionPath<
  T,
  From extends string,
  Path extends readonly string[],
> = Cfc<T, {
  projection: {
    from: From;
    path: CanonicalPointer<Path>;
  };
}>;
export type ProjectionOf<Root, PathTuple extends readonly string[]> =
  ProjectionPath<Root, "/", PathTuple>;
export type Projection<SourceRef> = SourceRef extends
  Ref<infer Root, infer Path extends readonly string[]>
  ? ProjectionOf<Root, Path>
  : never;
export type WriteAuthorizedBy<T, Binding> = Cfc<T, {
  writeAuthorizedBy: Binding;
}>;
export type TrustedActionWriteWithIntegrity<
  T,
  Binding,
  Action extends string,
  Pattern extends string,
  Integrity extends readonly [
    string,
    ...string[],
  ],
> = Cfc<WriteAuthorizedBy<T, Binding>, {
  uiContract: {
    helper: "UiAction";
    action: Action;
    trustedPattern: Pattern;
    requiredEventIntegrity: Integrity;
  };
}>;
export type TrustedActionWrite<
  T,
  Binding,
  Action extends string,
  Pattern extends string,
> = TrustedActionWriteWithIntegrity<T, Binding, Action, Pattern, [
  Pattern,
]>;
export type TrustedActionUiContract<
  T,
  Action extends string,
  Pattern extends string,
  Integrity extends readonly [
    string,
    ...string[],
  ] = [
    Pattern,
  ],
> = Cfc<T, {
  uiContract: {
    helper: "UiAction";
    action: Action;
    trustedPattern: Pattern;
    requiredEventIntegrity: Integrity;
  };
}>;
