apiVersion: v1
kind: Service
metadata:
  name: usuba-lb
spec:
  selector:
    app: usuba
  ports:
  - protocol: "TCP"
    targetPort: 8080
    port: 80 
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuba
spec:
  selector:
    matchLabels:
      app: usuba
  replicas: 1
  template:
    metadata:
      labels:
        app: usuba
    spec:
      containers:
      - name: usuba
        image: gcr.io/constellation-test-426817/usuba:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: minimal-ingress
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
#spec:
#  defaultBackend:
#    service:
#      name: usuba-lb 
#      port:
#        number: 8080
#  rules:
#  - http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: verification-service
#            port:
#              number: 9090
