// Generated by `deno task regenerate-favicons`.
// Source artwork lives in favicon-artwork.ts.

function decodePng(encoded: string): Uint8Array {
  return Uint8Array.fromBase64(encoded);
}

export const FAVICON_VERSION =
  "224994fd19ccb8f2b172c34e41235e68619bb9408f8bc17e7913a1abcbd14b9a";

export const FAVICON_PNG = {
  "good": decodePng(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAADHklEQVR4nNWXTUwTURDH57VUmiBSRJcW" +
      "0qbcMJpYLqIn8WiiEU5q4gHiwXggkZseCCUc9GRIOHEwcDBRT2A08aZ4UrywJhi50dBAPwxSRCJf3fU/" +
      "u2xZ7cfWbWvDL2l33tts3v/NzM68FVRlCgpobvFfUxUREqR2qUKESFU9mLZGiJRQVVklMSMcqpxYib7E" +
      "bE5yCmhtDYZ2FWUCC4YwLB0hZJfD0be8HJEx+oMsAZI3MESkhgm42rzkPtdOR860abaoc2PWGnVzi3YX" +
      "47Qzv0hbnxY0W0eEk/GlYRgZBH4ZsHgYj0MAUd2V83Ts9mVYpcFiNp6/o83XHzHCgkIMJGJLozA1MgI0" +
      "t6fTczDp+P2bVNvZDqt8bM8u0PdHz2DBs05nhxGOjADJF5jjmJdr57n48eSN7gnkRDK21IEpXYDUEuwm" +
      "JT3FcT7x+C5mKgOHY3VwQs8Jh7MnuRKZ1gXsx77+ehcdvXGJKslP5MPGixnC3oeRkGEBi5q9/hmV6GLT" +
      "SB8yPkiVZGc+onkBC79PxKNduMIDvsAa4u/xPn1Q9KtmFw5D/NZDOECkkAeNugCvHw4g8k0N47/yxHqG" +
      "8E+UjEeFwLUoAey69bFpWEQN/d1ZobK6b8aWgG93RmkvuQaLqEZqpJPj92AdYHXfjC0BCcRNQfwYp+Qh" +
      "aXwA1gFW983YEsAuTo1NwSLy9PdkudjqvhlbAsrJ4RTAMWbYvfkaFTccIwzNqCn5sC3ASDJ35yktxtw7" +
      "GK7tnANbs18xQplHMSu7AK5g5r6eD+6m9egnhSpqDgGBFJZoKKYUGzvdw663v0SIqT0dpBp4w/BMIXgj" +
      "WikmsY5m5NEEVL8ZVbsdHxxIfNQ00msZBruw+1cHJ5G0MWSq6UDCSD6/TCqd5SSq/JGMPidj0RCmYO5T" +
      "9UMpY+QCgbqrF4hzotRwsNs55puvPmBEOIfkOZYbmEVwTrjhCX4zXMF//DCJ6MXp11s506b/XpzJEsBo" +
      "4VDSk5wTGJYOYu5yOHsNt5vJKcBAfzuUkPZxSvg4RbHCdBGIdTyjfZySwyFztmMyJwUF/A9+A94RvzDx" +
      "GkU1AAAAAElFTkSuQmCC",
  ),
  "warn": decodePng(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAC60lEQVR4nMWWTUwTQRzF3xQM9QOoJrRb" +
      "SOty82KUxJ7UBBIOkhjlLCbycREuEg960YjRkwcTL+AFxUQ8mBiiMcGDCSTqCRM1XowXagl0W4xS8ING" +
      "2vVNzWJbutvdVegvmex//+m2772ZnY5AhfknAf5g+A0vSMZjLby4wrUARQl1Z4G7LOEBejRtbgwucC0g" +
      "oIRndegqiICIJrRYM0vHCA7HGO4b66t5Byyk1lyn4FiAqqq+H+nsLHTdN9rlx8pqFoOPPkOmsN3raYlG" +
      "o0v8mG0cC/Ar4SFAv3Io7MWdrgZIescX8Tq2ykpcTWqxITjAkQC1yH0kXMMuMBNLo288yW8TSztqPM1O" +
      "UnAkoJR7A7cp2Bagmrg3cJuCbQFW7g3cpGBLgFrGvYGbFGwJoPsxuj9zYv9OXD++B1ac4ys59fEnNYhb" +
      "iXhskC1LygpQFFXNIjPLEpMDjWiqr2Jlznwqg47hBVZyi65q1rRoFBaUFeDEvcGlp1/w5P13VuIe10I3" +
      "LBAcphS7l7ve7Zcp3gFnj9RjX2AbK+BD4ldBv9brsZ2CpYBi9x0jccwvrUHS5KvGZH+QFUr27aYgOEpS" +
      "7F7O/eGb81hJ82+I1NZ48Op8EyuU7NtdC6YCAsHQhK6jsytSi4vtPnaA+zPfcOP5V1bAhfbdOB3Zxcq8" +
      "bycFwbEBum+l+ynpZnIgiDrOqcEy14Ekvycp1Ze9juF4Lh2m0MYUplFESQEBJTSlA639XFD9R+vYcc/I" +
      "i2WMcIHyh6YT2lwbWwUIjgKs3LuhXAobBJi573uwiJlPcp8vT2SvF6OnGlj9wSoFwbGOlfv8lV4O+bx8" +
      "EwysUigQYOZeIl8refazgzwrytc2H7MUBEcOf6PaiWxmQj78sDdQ4P5/YJbCugDjmH2NO95J7nybwWPu" +
      "CZe5N8gDrHGMFxyc+7/H7Gec+83kGFOQU8l8e+QxPifAcI8txEghJ8AfDL2FjgMstw6Bd8n43MGcgEpS" +
      "cQG/AU7oqTD2PJ50AAAAAElFTkSuQmCC",
  ),
  "bad": decodePng(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACIUlEQVR4nNWV30obQRTGvzSlsUmVthRp" +
      "ipZTCg0ESpVa6J3JC/QBel/at6h9i5be+wD6AIl3goqKEIggBhUjQVSi8R/GeM7q6CbZ2VnXHcTfxeac" +
      "zMX327O7MzHcM0YBInp+eHJeQKs1xG1wYrGFZOJRvlKp7HGnxVeAwoYrAkhoBcgV/iH1FP+y79Abj/OK" +
      "mf1mEz9Lq1huHHGCv4SnAN0hXBFUokuAIghXBJFoE6AIwxUmiWsBshCu8JNwBMhiuEIn4Qj0p9/O2wxX" +
      "dErUqmvDlwKvB1v8g8KXrLVwhUjkZ0pcAbWt9VibwOzXj3y1z8j0El9vKTBXb+DPygZXwO/3A/jcl+Lq" +
      "BtO6m1AC3+bL2Dw55Qp4k3iCieEMVzeY1t2EEsjNlnBw1uQKSHPAZEeAad1NKAEZ8djViMc8RmxadxNK" +
      "IEoetoCMemq3jnLjmOsD/gc87mfIpHow+qKPa/3oFaEEZAP5v1HDeHWbOz3f06/wY6Dfd0MLJZDnt3z/" +
      "6i0ffSl3yned7OEOKB9eTmNqp84d0Ps4jsJIlitvtAJ+W7F8ZoK84TketRdFfjTqSyhqBGSS3VtxenAB" +
      "LXzK8GH01/Jh9IsPo7JzGGGxVl0fcgTIOY6bRZsSneHJRDxXUcexQBYldOG8xK0LsiDhFy60CQgUoYQp" +
      "XOgSECgCiSDhgqeAQHeQCBouaAUEcklwe3sM4YKvgEBhJQKEC0YB21wAk/bqMM78EUMAAAAASUVORK5C" +
      "YII=",
  ),
  "bad-crying": decodePng(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACw0lEQVR4nMWVXUiTURjH/3Pa1E1RSnND" +
      "62QfgiBqJXSp0GUJ3UV0nXUrdK0XQTdhUDd5E12EdG11F+hNVKRtEQwmZNPlZrMw9uG2bK7n2Tru6/3y" +
      "3YY/2LvneQ/s/3vPe3aOBYeMroAQom0ntbeATGaIWuNYLJ5mW92Y3+//TZ0qmgLCbLjEgISqgCgIP2dv" +
      "wmz/KbRYrTSiTzSdxoT3G1biCUrQllAUEBWES4xKlAmIKoRLjEgUCYgqhkv0JPYFRA3CJVoSWQFRw3CJ" +
      "mkRWoNN5wl3LcEmpRDi0PpwT6OrJ0BcWRvrLwoOpXcysBXGh1YHzrXb0NTfSXXV8O0l8isSxHIlh8qQL" +
      "LlsD3c3DEmMfvVQB4c2ApUhg6dIAXYtZph+b8K5SlcNlO4LrzmO40XWUujxzm7/wIvSThP9Ql2O2v5fE" +
      "7VQVc/H9F7oaFGB4Fp6HtjC/tY1keg/8quYGztBInmueFQSSKTRa6zDe0Y6bzg6SLX56yYEFmHG3j0Ry" +
      "T8ezMD/cR1UevfFCTAmMLnkR+5umCnBSwMuSAL3xQkwJ8FqY/vqdKmD6dHfZu9UbL8SUALPb5KAr0JCI" +
      "0dU8pgWW79xHfSKOwWf3qDOPKYGoqxcfJh9j1f0O6w/u4u3GBqL/33lLvRWj7a24Qqtfa+olpgSCI5fx" +
      "KA68efqQOnVudR+nTydV6pgSmFr7gdehMFXAWYcdY22O/aflBbi4HcltscRVmokpWohqqAoobcUM73Iz" +
      "/iBVyE4zr3Il+F/wijYrZlK4ynZLRnkrdvZ4kMFgH+1wTxQOIymgFS6REkoCHH6bDiMfz5QFn8OhwFBW" +
      "QGSP4/SilkSllIY326yjfnkcM6KGEmrhNERtAaIGElrhTJEAI6oooRfOlAkwogoSRsIZRQFGVCBhNJxR" +
      "FWBEgQS1B0cnnNEUYIRZCQPhjK5ArfkHJ0gkP3COH7oAAAAASUVORK5CYII=",
  ),
} as const;
