// Generated by `deno task regenerate-favicons`.
// Source artwork lives in favicon-artwork.ts.

function decodePng(encoded: string): Uint8Array {
  return Uint8Array.fromBase64(encoded);
}

export const FAVICON_VERSION =
  "ff2c588d7e036104b8bc81803f6737b08ee1fa7c2ab7e03570e1f0f9757559bd";

export const FAVICON_PNG = {
  "good": decodePng(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAADJklEQVR4nNWXMUwTYRTH39emBFOjJYGD" +
      "UlqLMZpAjcfCZCJODpIomshG1M3o4uQmZXQwcdDopIYNE0UTXAUTJxZqLCQy2EqB0pOkQGwgkvb8v2uv" +
      "HPbaa67Uhl/S6/u+S/P+99777r0KajAVBbR3+q+oOSELUgdUIWRSVQ+2rRFiQ6hqRCUxIxxqJLWa+IBd" +
      "U0wF+HxBeTeXewWHMpa1I0TE5XDcWlmJR7DaR4kAqSMwSqSGCRwJeuhYfxe5e9uoubuFnG4Xdq3JZnZp" +
      "J5amzPwv2ppdpu34BnYZEVbWlsZgFBH4FIHzMJxDAFHr5dPkvd0HqzZYjDIRpfWPi1jBoRD3U8mlJzA1" +
      "igK0sGezczDpxIPzeHIfrINja3aFfj76AovI5XT26ekoCpC8gTnO+UE9uRnJl3P5SKAmlOSS5kQTIHUG" +
      "r1IuO8k5P/X4EnbqA6cj9vATaTXhcA4pq/H3eQGF3LffCJE03Ev1RJmYp9SbKCwxhoIMawLaO/wzKtGF" +
      "k2MXyR2SsFM/MlGFfoxOExx/Tq0lBvCNCHgDaeTf0zN+reqjZhdOw8LIOwRAbKAOWvICOvwIANHZt8O4" +
      "1p9v1ydwRTrWEqJqARy65WezsIi67vaXpMrqvhFbAr7fmaI/SgYWUZPkpjPPB2HtYXXfiC0BnDfOH9PU" +
      "Bgcv9juwum/ElgAtxE8LIb5XGmKr+0ZsCThIDqeAhZFJXPPhLdeouOHoaegZH8LVHJsC9oqMZ4SjIcwI" +
      "wRasiHbiafodzfd+hl9m/FIrhy0B7NzY18vB3VQaDmkiymEiIID2pB5n1ZV+yHC1c6i5o2XmFewQJiap" +
      "MD35KlY/ww/C0cS7eBPNyKMJaHwzanQ7lvSBBINnN6JglQa7cPhjePrtWHr/QMJIXn+EVDrHRVT/kYy+" +
      "KsmEjC2YBRo+lDJ6LRBoHcRxQk3Umg4Ou4Kcr08tYgWH5cZyHaMIrgmOBB+zZhyzasWw053CMU1Px4pt" +
      "+l/nTIkARktHLvuaUBNY1g5y7nI4b+phN2IqQEfSTkdO1v6ckpAJLytsV4HYxG+0P6fkcES42rFpSkUB" +
      "/4O/Cam/MHcVf0MAAAAASUVORK5CYII=",
  ),
  "warn": decodePng(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAC3klEQVR4nMWWXUhTYRzGn3dGpmSIxHY2" +
      "2TgDqSDIVOg27UoocN1VNxkkJHhRgUE38+OmywgEA5MMoi5VKPAq9TbIsm76EDYmujMJkwzFaDs97+yY" +
      "mztn5xw/9oM/57//NvY8z3nPu1egxOxKgNcfes8LlpKJBl5c4VqAogTbM8BTtvAANzRtfgQucC3Ap4Ri" +
      "OnQVREDEU1oizNYxguUYw72/ppyvgOTyhusUHAtQVbV6bSMTg65XD3adwup6GveGv0GmUHHE0xCPx1f4" +
      "Mds4FuBVQr2A3tNYV4XHFCC5NfAZM3Or7ETfkpbohQMcCVDz3DdRhOQdf7yTIiDESmW5J+wkBUcCCrk3" +
      "cJuCbQGqiXsDtynYFmDl3sBNCrYEqEXcG7hJwZYAuh+h++sXzx1Hz7UwrOgensP0px/UIB6lkonbHFki" +
      "WJYoiqpmkI6xxVi0HoGaw+zMWVz+jUj/LDu5RZeFNS0ehwVFBThxb9D3IobXb7+zE8+4FtphgWCZku/+" +
      "1/ofPJlY5CvgZmsAJ2or2QFfF9Zy5kcrDtlOwVJAvvtI/0dGvAFJgP8DY9Ez7FBwbjcFwSpIvnt57y/c" +
      "n2EKaU5Al2V486CRHQrO7a4FUwE+f3BU1xG5ct6Hu5dDnAAvp1N4OJpgB9zh7Crfk5jN7aQgWDug+2a6" +
      "n5Ruxum+ilcD+e8n2T6TFJrLWRtTkOkwhRamMIU8CgrwKcFJHWjuaK1FBxfVbhji4hyaWJA/NJXS5ls4" +
      "ykGwcrBy74ZiKewQYOa+c+ALt9qf7IrTVHcMg10n2W1ilYJgbWHlfvtKL4b8vnwSDKxSyBFg5l4iHyt5" +
      "9rODPCvKx3Y7ZikIVhZvQI0gkx6VX37efTrH/V5glsKWAOOYHeWOd4k7337wintCP/cGeYA1jvGCxXv/" +
      "/5g9Ht3cXveLNm7b8lZ6/h3jswIM9zhAjBSyArz+4AfoqGd7cAjMLiXnz2YFlJKSC/gL42ypMOYMleAA" +
      "AAAASUVORK5CYII=",
  ),
  "bad": decodePng(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACIUlEQVR4nNWV30obQRTGvzSlsUmVthRp" +
      "ipZTCg0ESpVa6J3JC/QBel/at6h9i5be+wD6AIl3goqKEIggBhUjQVSi8R/GeM7q6CbZ2VnXHcTfxeac" +
      "zMX327O7MzHcM0YBInp+eHJeQKs1xG1wYrGFZOJRvlKp7HGnxVeAwoYrAkhoBcgV/iH1FP+y79Abj/OK" +
      "mf1mEz9Lq1huHHGCv4SnAN0hXBFUokuAIghXBJFoE6AIwxUmiWsBshCu8JNwBMhiuEIn4Qj0p9/O2wxX" +
      "dErUqmvDlwKvB1v8g8KXrLVwhUjkZ0pcAbWt9VibwOzXj3y1z8j0El9vKTBXb+DPygZXwO/3A/jcl+Lq" +
      "BtO6m1AC3+bL2Dw55Qp4k3iCieEMVzeY1t2EEsjNlnBw1uQKSHPAZEeAad1NKAEZ8djViMc8RmxadxNK" +
      "IEoetoCMemq3jnLjmOsD/gc87mfIpHow+qKPa/3oFaEEZAP5v1HDeHWbOz3f06/wY6Dfd0MLJZDnt3z/" +
      "6i0ffSl3yned7OEOKB9eTmNqp84d0Ps4jsJIlitvtAJ+W7F8ZoK84TketRdFfjTqSyhqBGSS3VtxenAB" +
      "LXzK8GH01/Jh9IsPo7JzGGGxVl0fcgTIOY6bRZsSneHJRDxXUcexQBYldOG8xK0LsiDhFy60CQgUoYQp" +
      "XOgSECgCiSDhgqeAQHeQCBouaAUEcklwe3sM4YKvgEBhJQKEC0YB21wAk/bqMM78EUMAAAAASUVORK5C" +
      "YII=",
  ),
  "bad-crying": decodePng(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACw0lEQVR4nMWVXUiTURjH/3Pa1E1RSnND" +
      "62QfgiBqJXSp0GUJ3UV0nXUrdK0XQTdhUDd5E12EdG11F+hNVKRtEQwmZNPlZrMw9uG2bK7n2Tru6/3y" +
      "3YY/2LvneQ/s/3vPe3aOBYeMroAQom0ntbeATGaIWuNYLJ5mW92Y3+//TZ0qmgLCbLjEgISqgCgIP2dv" +
      "wmz/KbRYrTSiTzSdxoT3G1biCUrQllAUEBWES4xKlAmIKoRLjEgUCYgqhkv0JPYFRA3CJVoSWQFRw3CJ" +
      "mkRWoNN5wl3LcEmpRDi0PpwT6OrJ0BcWRvrLwoOpXcysBXGh1YHzrXb0NTfSXXV8O0l8isSxHIlh8qQL" +
      "LlsD3c3DEmMfvVQB4c2ApUhg6dIAXYtZph+b8K5SlcNlO4LrzmO40XWUujxzm7/wIvSThP9Ql2O2v5fE" +
      "7VQVc/H9F7oaFGB4Fp6HtjC/tY1keg/8quYGztBInmueFQSSKTRa6zDe0Y6bzg6SLX56yYEFmHG3j0Ry" +
      "T8ezMD/cR1UevfFCTAmMLnkR+5umCnBSwMuSAL3xQkwJ8FqY/vqdKmD6dHfZu9UbL8SUALPb5KAr0JCI" +
      "0dU8pgWW79xHfSKOwWf3qDOPKYGoqxcfJh9j1f0O6w/u4u3GBqL/33lLvRWj7a24Qqtfa+olpgSCI5fx" +
      "KA68efqQOnVudR+nTydV6pgSmFr7gdehMFXAWYcdY22O/aflBbi4HcltscRVmokpWohqqAoobcUM73Iz" +
      "/iBVyE4zr3Il+F/wijYrZlK4ynZLRnkrdvZ4kMFgH+1wTxQOIymgFS6REkoCHH6bDiMfz5QFn8OhwFBW" +
      "QGSP4/SilkSllIY326yjfnkcM6KGEmrhNERtAaIGElrhTJEAI6oooRfOlAkwogoSRsIZRQFGVCBhNJxR" +
      "FWBEgQS1B0cnnNEUYIRZCQPhjK5ArfkHJ0gkP3COH7oAAAAASUVORK5CYII=",
  ),
} as const;
