name: "Deno Setup"
description: "Setup deno"
inputs:
  cache:
    description: "Load deno dependencies from github cache"
    default: true
runs:
  using: "composite"
  steps:
    # Keep in sync with `./tasks/check.sh` version
    - name: 🦕 Setup Deno 2.6.4
      uses: denoland/setup-deno@v2
      with:
        deno-version: "2.6.4"

    # Cache version: bump to invalidate all caches (e.g., v1 -> v2)
    - name: 📦 Cache Deno dependencies
      if: inputs.cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.deno
          ~/.cache/deno
        key: v2-${{ runner.os }}-deno-2.6.4-${{ hashFiles('**/deno.json', '**/deno.lock') }}
