name: "Deno Setup"
description: "Setup deno"
inputs:
  cache:
    description: "Load deno dependencies from github cache"
    default: true
  deno-version:
    description: "Deno version to install"
    default: "2.6.4"
runs:
  using: "composite"
  steps:
    # Keep in sync with `./tasks/check.sh` version
    - name: 🦕 Setup Deno ${{ inputs.deno-version }}
      uses: denoland/setup-deno@v2
      with:
        deno-version: ${{ inputs.deno-version }}

    # Cache version: bump to invalidate all caches (e.g., v1 -> v2)
    - name: 📦 Cache Deno dependencies
      if: inputs.cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.deno
          ~/.cache/deno
        key: v2-${{ runner.os }}-deno-${{ inputs.deno-version }}-${{ hashFiles('**/deno.json', '**/deno.lock') }}
