/** Dark ink-and-brass theme shared by the dungeon pattern family. */
export const DUNGEON_THEME = {
  fontFamily: "Georgia, 'Times New Roman', serif",
  monoFontFamily: "'SFMono-Regular', Consolas, 'Liberation Mono', monospace",
  borderRadius: "10px",
  density: "comfortable" as const,
  colorScheme: "dark" as const,
  colors: {
    primary: "#d6a84b",
    primaryForeground: "#17130c",
    secondary: "#252b30",
    secondaryForeground: "#e8ddc5",
    background: "#101417",
    surface: "#1a2024",
    surfaceHover: "#222b30",
    text: "#eee5d3",
    textMuted: "#a99d87",
    border: "#4d493f",
    borderMuted: "#302f2a",
    accent: "#8fb996",
    accentForeground: "#101713",
    success: "#8fb996",
    successForeground: "#101713",
    warning: "#d6a84b",
    warningForeground: "#17130c",
    error: "#c97365",
    errorForeground: "#190b09",
  },
};
