import type { ReadBudgetLimits } from "./topics-read-budget.ts";

/**
 * The Topics read-budget limits, by case, phase, and gated count: the
 * largest count five rounds observed, plus 10% and rounded up, or the
 * counts observed where they differed between rounds.
 * `deno run -A --frozen scripts/topics-computation-cost.ts --derive-limits`
 * prints this module, and `topics-read-budget.ts` says what each count is.
 */
export const TOPICS_READ_BUDGET_LIMITS: ReadBudgetLimits = {
  "pivot/low-degree/mentions-3/topics-4/topic-open": {
    initialization: {
      attemptTotal: 48,
      bodyTotal: 48,
      bodyPerRun: 24,
      graphNodes: 36,
      graphEdges: 57,
    },
    "mention removal": {
      attemptTotal: 38,
      bodyTotal: 38,
      bodyPerRun: 22,
      graphNodes: 36,
      graphEdges: 55,
    },
    "mention insertion": {
      attemptTotal: 40,
      bodyTotal: 40,
      bodyPerRun: 24,
      graphNodes: 36,
      graphEdges: 57,
    },
    "same-count retarget": {
      attemptTotal: 39,
      bodyTotal: 39,
      bodyPerRun: 24,
      graphNodes: 36,
      graphEdges: 55,
    },
    "comment append": {
      attemptTotal: 10,
      bodyTotal: 10,
      bodyPerRun: 10,
      graphNodes: 37,
      graphEdges: 57,
    },
    "comment edit": {
      attemptTotal: 10,
      bodyTotal: 10,
      bodyPerRun: 10,
      graphNodes: 37,
      graphEdges: 57,
    },
    "comment retraction": {
      attemptTotal: 10,
      bodyTotal: 10,
      bodyPerRun: 10,
      graphNodes: 37,
      graphEdges: 57,
    },
    "link removal": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 37,
      graphEdges: 57,
    },
    "unrelated sibling edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 37,
      graphEdges: 57,
    },
    reopen: {
      attemptTotal: 49,
      bodyTotal: 49,
      bodyPerRun: 24,
      graphNodes: 37,
      graphEdges: 57,
    },
  },
  "pivot/low-degree/mentions-3/topics-4/all-backlinks": {
    initialization: {
      attemptTotal: 90,
      bodyTotal: 90,
      bodyPerRun: 24,
      graphNodes: 43,
      graphEdges: 110,
    },
    "mention removal": {
      attemptTotal: 38,
      bodyTotal: 38,
      bodyPerRun: 22,
      graphNodes: 43,
      graphEdges: 109,
    },
    "mention insertion": {
      attemptTotal: 40,
      bodyTotal: 40,
      bodyPerRun: 24,
      graphNodes: 43,
      graphEdges: 110,
    },
    "same-count retarget": {
      attemptTotal: 39,
      bodyTotal: 39,
      bodyPerRun: 24,
      graphNodes: 43,
      graphEdges: 109,
    },
    "comment append": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 43,
      graphEdges: 109,
    },
    "comment edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 43,
      graphEdges: 109,
    },
    "comment retraction": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 43,
      graphEdges: 109,
    },
    "link removal": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 43,
      graphEdges: 109,
    },
    "unrelated sibling edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 43,
      graphEdges: 109,
    },
    reopen: {
      attemptTotal: 88,
      bodyTotal: 88,
      bodyPerRun: 24,
      graphNodes: 43,
      graphEdges: 109,
    },
  },
  "thread/comments-1/links-1/aggregates": {
    initialization: {
      attemptTotal: 66,
      bodyTotal: 66,
      bodyPerRun: 14,
      graphNodes: 58,
      graphEdges: 58,
    },
    "mention removal": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 58,
      graphEdges: 58,
    },
    "mention insertion": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 58,
      graphEdges: 58,
    },
    "same-count retarget": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 58,
      graphEdges: 58,
    },
    "comment append": {
      attemptTotal: 24,
      bodyTotal: 24,
      bodyPerRun: 18,
      graphNodes: 59,
      graphEdges: 60,
    },
    "comment edit": {
      attemptTotal: 24,
      bodyTotal: 24,
      bodyPerRun: 18,
      graphNodes: 59,
      graphEdges: 60,
    },
    "comment retraction": {
      attemptTotal: 24,
      bodyTotal: 24,
      bodyPerRun: 18,
      graphNodes: 59,
      graphEdges: 60,
    },
    "link removal": {
      attemptTotal: 18,
      bodyTotal: 18,
      bodyPerRun: 18,
      graphNodes: 59,
      graphEdges: 60,
    },
    "unrelated sibling edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 59,
      graphEdges: 60,
    },
    reopen: {
      attemptTotal: 73,
      bodyTotal: 73,
      bodyPerRun: 18,
      graphNodes: 59,
      graphEdges: 60,
    },
  },
  "thread/comments-100/links-3/aggregates": {
    initialization: {
      attemptTotal: 2706,
      bodyTotal: 2706,
      bodyPerRun: 456,
      graphNodes: 502,
      graphEdges: 938,
    },
    "mention removal": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 502,
      graphEdges: 938,
    },
    "mention insertion": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 502,
      graphEdges: 938,
    },
    "same-count retarget": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 502,
      graphEdges: 938,
    },
    "comment append": {
      attemptTotal: 684,
      bodyTotal: 684,
      bodyPerRun: 460,
      graphNodes: 503,
      graphEdges: 940,
    },
    "comment edit": {
      attemptTotal: 684,
      bodyTotal: 684,
      bodyPerRun: 460,
      graphNodes: 503,
      graphEdges: 940,
    },
    "comment retraction": {
      attemptTotal: 684,
      bodyTotal: 684,
      bodyPerRun: 460,
      graphNodes: 503,
      graphEdges: 940,
    },
    "link removal": {
      attemptTotal: 460,
      bodyTotal: 460,
      bodyPerRun: 460,
      graphNodes: 503,
      graphEdges: 940,
    },
    "unrelated sibling edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 503,
      graphEdges: 940,
    },
    reopen: {
      attemptTotal: 2713,
      bodyTotal: 2713,
      bodyPerRun: 460,
      graphNodes: 503,
      graphEdges: 940,
    },
  },
  "thread/comments-3/links-100/aggregates": {
    initialization: {
      attemptTotal: 1426,
      bodyTotal: 1426,
      bodyPerRun: 349,
      graphNodes: 502,
      graphEdges: 511,
    },
    "mention removal": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 502,
      graphEdges: 511,
    },
    "mention insertion": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 502,
      graphEdges: 511,
    },
    "same-count retarget": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 502,
      graphEdges: 511,
    },
    "comment append": {
      attemptTotal: 363,
      bodyTotal: 363,
      bodyPerRun: 354,
      graphNodes: 503,
      graphEdges: 513,
    },
    "comment edit": {
      attemptTotal: 363,
      bodyTotal: 363,
      bodyPerRun: 354,
      graphNodes: 503,
      graphEdges: 513,
    },
    "comment retraction": {
      attemptTotal: 363,
      bodyTotal: 363,
      bodyPerRun: 354,
      graphNodes: 503,
      graphEdges: 513,
    },
    "link removal": {
      attemptTotal: 354,
      bodyTotal: 354,
      bodyPerRun: 354,
      graphNodes: 503,
      graphEdges: 513,
    },
    "unrelated sibling edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 503,
      graphEdges: 513,
    },
    reopen: {
      attemptTotal: 1433,
      bodyTotal: 1433,
      bodyPerRun: 354,
      graphNodes: 503,
      graphEdges: 513,
    },
  },
  "pivot/single-bucket/mentions-4/topics-32/topic-open": {
    initialization: {
      attemptTotal: 325,
      bodyTotal: 325,
      bodyPerRun: 208,
      graphNodes: 97,
      graphEdges: 272,
    },
    "mention removal": {
      attemptTotal: 312,
      bodyTotal: 312,
      bodyPerRun: 204,
      graphNodes: 97,
      graphEdges: 271,
    },
    "mention insertion": {
      attemptTotal: 314,
      bodyTotal: 314,
      bodyPerRun: 205,
      graphNodes: 97,
      graphEdges: 272,
    },
    "same-count retarget": {
      attemptTotal: 313,
      bodyTotal: 313,
      bodyPerRun: 205,
      graphNodes: 97,
      graphEdges: 271,
    },
    "comment append": {
      attemptTotal: 10,
      bodyTotal: 10,
      bodyPerRun: 10,
      graphNodes: 98,
      graphEdges: 272,
    },
    "comment edit": {
      attemptTotal: 10,
      bodyTotal: 10,
      bodyPerRun: 10,
      graphNodes: 98,
      graphEdges: 272,
    },
    "comment retraction": {
      attemptTotal: 10,
      bodyTotal: 10,
      bodyPerRun: 10,
      graphNodes: 98,
      graphEdges: 272,
    },
    "link removal": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 98,
      graphEdges: 272,
    },
    "unrelated sibling edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 98,
      graphEdges: 272,
    },
    reopen: {
      attemptTotal: 323,
      bodyTotal: 323,
      bodyPerRun: 205,
      graphNodes: 98,
      graphEdges: 272,
    },
  },
  "pivot/single-bucket/mentions-4/topics-32/all-backlinks": {
    initialization: {
      attemptTotal: 2636,
      bodyTotal: 2636,
      bodyPerRun: 208,
      graphNodes: 259,
      graphEdges: 2719,
    },
    "mention removal": {
      attemptTotal: 312,
      bodyTotal: 312,
      bodyPerRun: 204,
      graphNodes: 259,
      graphEdges: 2717,
    },
    "mention insertion": {
      attemptTotal: 314,
      bodyTotal: 314,
      bodyPerRun: 205,
      graphNodes: 259,
      graphEdges: 2719,
    },
    "same-count retarget": {
      attemptTotal: 389,
      bodyTotal: 389,
      bodyPerRun: 205,
      graphNodes: 259,
      graphEdges: 2719,
    },
    "comment append": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 259,
      graphEdges: 2719,
    },
    "comment edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 259,
      graphEdges: 2719,
    },
    "comment retraction": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 259,
      graphEdges: 2719,
    },
    "link removal": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 259,
      graphEdges: 2719,
    },
    "unrelated sibling edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 259,
      graphEdges: 2719,
    },
    reopen: {
      attemptTotal: 2633,
      bodyTotal: 2633,
      bodyPerRun: 205,
      graphNodes: 259,
      graphEdges: 2719,
    },
  },
  "pivot/high-degree/mentions-4/topics-32/topic-open": {
    initialization: {
      attemptTotal: 329,
      bodyTotal: 329,
      bodyPerRun: 213,
      graphNodes: 97,
      graphEdges: 272,
    },
    "mention removal": {
      attemptTotal: 319,
      bodyTotal: 319,
      bodyPerRun: 212,
      graphNodes: 97,
      graphEdges: 271,
    },
    "mention insertion": {
      attemptTotal: 322,
      bodyTotal: 322,
      bodyPerRun: 213,
      graphNodes: 97,
      graphEdges: 272,
    },
    "same-count retarget": {
      attemptTotal: 321,
      bodyTotal: 321,
      bodyPerRun: 213,
      graphNodes: 97,
      graphEdges: 271,
    },
    "comment append": {
      attemptTotal: 10,
      bodyTotal: 10,
      bodyPerRun: 10,
      graphNodes: 98,
      graphEdges: 272,
    },
    "comment edit": {
      attemptTotal: 10,
      bodyTotal: 10,
      bodyPerRun: 10,
      graphNodes: 98,
      graphEdges: 272,
    },
    "comment retraction": {
      attemptTotal: 10,
      bodyTotal: 10,
      bodyPerRun: 10,
      graphNodes: 98,
      graphEdges: 272,
    },
    "link removal": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 98,
      graphEdges: 272,
    },
    "unrelated sibling edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 98,
      graphEdges: 272,
    },
    reopen: {
      attemptTotal: 330,
      bodyTotal: 330,
      bodyPerRun: 213,
      graphNodes: 98,
      graphEdges: 272,
    },
  },
  "pivot/high-degree/mentions-4/topics-32/all-backlinks": {
    initialization: {
      attemptTotal: 2747,
      bodyTotal: 2747,
      bodyPerRun: 213,
      graphNodes: 259,
      graphEdges: 2825,
    },
    "mention removal": {
      attemptTotal: 319,
      bodyTotal: 319,
      bodyPerRun: 212,
      graphNodes: 259,
      graphEdges: 2824,
    },
    "mention insertion": {
      attemptTotal: 322,
      bodyTotal: 322,
      bodyPerRun: 213,
      graphNodes: 259,
      graphEdges: 2825,
    },
    "same-count retarget": {
      attemptTotal: 396,
      bodyTotal: 396,
      bodyPerRun: 213,
      graphNodes: 259,
      graphEdges: 2825,
    },
    "comment append": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 259,
      graphEdges: 2825,
    },
    "comment edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 259,
      graphEdges: 2825,
    },
    "comment retraction": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 259,
      graphEdges: 2825,
    },
    "link removal": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 259,
      graphEdges: 2825,
    },
    "unrelated sibling edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 259,
      graphEdges: 2825,
    },
    reopen: {
      attemptTotal: 2747,
      bodyTotal: 2747,
      bodyPerRun: 213,
      graphNodes: 259,
      graphEdges: 2825,
    },
  },
  "pivot/low-degree/mentions-16/topics-32/topic-open": {
    initialization: {
      attemptTotal: 735,
      bodyTotal: 735,
      bodyPerRun: 635,
      graphNodes: 97,
      graphEdges: 256,
    },
    "mention removal": {
      attemptTotal: 725,
      bodyTotal: 725,
      bodyPerRun: 634,
      graphNodes: 97,
      graphEdges: 255,
    },
    "mention insertion": {
      attemptTotal: 728,
      bodyTotal: 728,
      bodyPerRun: 635,
      graphNodes: 97,
      graphEdges: 256,
    },
    "same-count retarget": {
      attemptTotal: 726,
      bodyTotal: 726,
      bodyPerRun: 635,
      graphNodes: 97,
      graphEdges: 255,
    },
    "comment append": {
      attemptTotal: 10,
      bodyTotal: 10,
      bodyPerRun: 10,
      graphNodes: 98,
      graphEdges: 256,
    },
    "comment edit": {
      attemptTotal: 10,
      bodyTotal: 10,
      bodyPerRun: 10,
      graphNodes: 98,
      graphEdges: 256,
    },
    "comment retraction": {
      attemptTotal: 10,
      bodyTotal: 10,
      bodyPerRun: 10,
      graphNodes: 98,
      graphEdges: 256,
    },
    "link removal": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 98,
      graphEdges: 256,
    },
    "unrelated sibling edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 98,
      graphEdges: 256,
    },
    reopen: {
      attemptTotal: 736,
      bodyTotal: 736,
      bodyPerRun: 635,
      graphNodes: 98,
      graphEdges: 256,
    },
  },
  "pivot/low-degree/mentions-16/topics-32/all-backlinks": {
    initialization: {
      attemptTotal: 3592,
      bodyTotal: 3592,
      bodyPerRun: 635,
      graphNodes: 259,
      graphEdges: 3248,
    },
    "mention removal": {
      attemptTotal: 725,
      bodyTotal: 725,
      bodyPerRun: 634,
      graphNodes: 259,
      graphEdges: 3247,
    },
    "mention insertion": {
      attemptTotal: 728,
      bodyTotal: 728,
      bodyPerRun: 635,
      graphNodes: 259,
      graphEdges: 3248,
    },
    "same-count retarget": {
      attemptTotal: 820,
      bodyTotal: 820,
      bodyPerRun: 635,
      graphNodes: 259,
      graphEdges: 3248,
    },
    "comment append": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 259,
      graphEdges: 3248,
    },
    "comment edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 259,
      graphEdges: 3248,
    },
    "comment retraction": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 259,
      graphEdges: 3248,
    },
    "link removal": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 259,
      graphEdges: 3248,
    },
    "unrelated sibling edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 259,
      graphEdges: 3248,
    },
    reopen: {
      attemptTotal: 3592,
      bodyTotal: 3592,
      bodyPerRun: 635,
      graphNodes: 259,
      graphEdges: 3248,
    },
  },
};
