import type { ReadBudgetLimits } from "./topics-read-budget.ts";

/**
 * The Topics read-budget limits, by case, phase, and gated count: the
 * largest count five rounds observed, plus 10% and rounded up, or the
 * counts observed where they differed between rounds.
 * `deno run -A --frozen scripts/topics-computation-cost.ts --derive-limits`
 * prints this module, and `topics-read-budget.ts` says what each count is.
 */
export const TOPICS_READ_BUDGET_LIMITS: ReadBudgetLimits = {
  "pivot/low-degree/mentions-3/topics-4/topic-open": {
    initialization: {
      attemptTotal: 48,
      bodyTotal: 48,
      bodyPerRun: 24,
      graphNodes: 36,
      graphEdges: 57,
    },
    "mention removal": {
      attemptTotal: 38,
      bodyTotal: 38,
      bodyPerRun: 22,
      graphNodes: 36,
      graphEdges: 55,
    },
    "mention insertion": {
      attemptTotal: 40,
      bodyTotal: 40,
      bodyPerRun: 24,
      graphNodes: 36,
      graphEdges: 57,
    },
    "same-count retarget": {
      attemptTotal: 39,
      bodyTotal: 39,
      bodyPerRun: 24,
      graphNodes: 36,
      graphEdges: 55,
    },
    "comment append": {
      attemptTotal: 10,
      bodyTotal: 10,
      bodyPerRun: 10,
      graphNodes: 37,
      graphEdges: 57,
    },
    "comment edit": {
      attemptTotal: 10,
      bodyTotal: 10,
      bodyPerRun: 10,
      graphNodes: 37,
      graphEdges: 57,
    },
    "comment retraction": {
      attemptTotal: 10,
      bodyTotal: 10,
      bodyPerRun: 10,
      graphNodes: 37,
      graphEdges: 57,
    },
    "link removal": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 37,
      graphEdges: 57,
    },
    "unrelated sibling edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 37,
      graphEdges: 57,
    },
    reopen: {
      attemptTotal: 49,
      bodyTotal: 49,
      bodyPerRun: 24,
      graphNodes: 37,
      graphEdges: 57,
    },
  },
  "pivot/low-degree/mentions-3/topics-4/all-backlinks": {
    initialization: {
      attemptTotal: 90,
      bodyTotal: 90,
      bodyPerRun: 24,
      graphNodes: 43,
      graphEdges: 110,
    },
    "mention removal": {
      attemptTotal: 38,
      bodyTotal: 38,
      bodyPerRun: 22,
      graphNodes: 43,
      graphEdges: 109,
    },
    "mention insertion": {
      attemptTotal: 40,
      bodyTotal: 40,
      bodyPerRun: 24,
      graphNodes: 43,
      graphEdges: 110,
    },
    "same-count retarget": {
      attemptTotal: 39,
      bodyTotal: 39,
      bodyPerRun: 24,
      graphNodes: 43,
      graphEdges: 109,
    },
    "comment append": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 43,
      graphEdges: 109,
    },
    "comment edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 43,
      graphEdges: 109,
    },
    "comment retraction": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 43,
      graphEdges: 109,
    },
    "link removal": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 43,
      graphEdges: 109,
    },
    "unrelated sibling edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 43,
      graphEdges: 109,
    },
    reopen: {
      attemptTotal: 88,
      bodyTotal: 88,
      bodyPerRun: 24,
      graphNodes: 43,
      graphEdges: 109,
    },
  },
  "thread/comments-1/links-1/aggregates": {
    initialization: {
      attemptTotal: 66,
      bodyTotal: 66,
      bodyPerRun: 14,
      graphNodes: 58,
      graphEdges: 58,
    },
    "mention removal": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 58,
      graphEdges: 58,
    },
    "mention insertion": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 58,
      graphEdges: 58,
    },
    "same-count retarget": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 58,
      graphEdges: 58,
    },
    "comment append": {
      attemptTotal: 24,
      bodyTotal: 24,
      bodyPerRun: 18,
      graphNodes: 59,
      graphEdges: 60,
    },
    "comment edit": {
      attemptTotal: 24,
      bodyTotal: 24,
      bodyPerRun: 18,
      graphNodes: 59,
      graphEdges: 60,
    },
    "comment retraction": {
      attemptTotal: 24,
      bodyTotal: 24,
      bodyPerRun: 18,
      graphNodes: 59,
      graphEdges: 60,
    },
    "link removal": {
      attemptTotal: 18,
      bodyTotal: 18,
      bodyPerRun: 18,
      graphNodes: 59,
      graphEdges: 60,
    },
    "unrelated sibling edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 59,
      graphEdges: 60,
    },
    reopen: {
      attemptTotal: 73,
      bodyTotal: 73,
      bodyPerRun: 18,
      graphNodes: 59,
      graphEdges: 60,
    },
  },
  "thread/comments-100/links-3/aggregates": {
    initialization: {
      attemptTotal: 2706,
      bodyTotal: 2706,
      bodyPerRun: 456,
      graphNodes: 502,
      graphEdges: 938,
    },
    "mention removal": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 502,
      graphEdges: 938,
    },
    "mention insertion": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 502,
      graphEdges: 938,
    },
    "same-count retarget": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 502,
      graphEdges: 938,
    },
    "comment append": {
      attemptTotal: 684,
      bodyTotal: 684,
      bodyPerRun: 460,
      graphNodes: 503,
      graphEdges: 940,
    },
    "comment edit": {
      attemptTotal: 684,
      bodyTotal: 684,
      bodyPerRun: 460,
      graphNodes: 503,
      graphEdges: 940,
    },
    "comment retraction": {
      attemptTotal: 684,
      bodyTotal: 684,
      bodyPerRun: 460,
      graphNodes: 503,
      graphEdges: 940,
    },
    "link removal": {
      attemptTotal: 460,
      bodyTotal: 460,
      bodyPerRun: 460,
      graphNodes: 503,
      graphEdges: 940,
    },
    "unrelated sibling edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 503,
      graphEdges: 940,
    },
    reopen: {
      attemptTotal: 2713,
      bodyTotal: 2713,
      bodyPerRun: 460,
      graphNodes: 503,
      graphEdges: 940,
    },
  },
  "thread/comments-3/links-100/aggregates": {
    initialization: {
      attemptTotal: 1426,
      bodyTotal: 1426,
      bodyPerRun: 349,
      graphNodes: 502,
      graphEdges: 511,
    },
    "mention removal": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 502,
      graphEdges: 511,
    },
    "mention insertion": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 502,
      graphEdges: 511,
    },
    "same-count retarget": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 502,
      graphEdges: 511,
    },
    "comment append": {
      attemptTotal: 363,
      bodyTotal: 363,
      bodyPerRun: 354,
      graphNodes: 503,
      graphEdges: 513,
    },
    "comment edit": {
      attemptTotal: 363,
      bodyTotal: 363,
      bodyPerRun: 354,
      graphNodes: 503,
      graphEdges: 513,
    },
    "comment retraction": {
      attemptTotal: 363,
      bodyTotal: 363,
      bodyPerRun: 354,
      graphNodes: 503,
      graphEdges: 513,
    },
    "link removal": {
      attemptTotal: 354,
      bodyTotal: 354,
      bodyPerRun: 354,
      graphNodes: 503,
      graphEdges: 513,
    },
    "unrelated sibling edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 503,
      graphEdges: 513,
    },
    reopen: {
      attemptTotal: 1433,
      bodyTotal: 1433,
      bodyPerRun: 354,
      graphNodes: 503,
      graphEdges: 513,
    },
  },
  "pivot/single-bucket/mentions-4/topics-128/topic-open": {
    initialization: {
      attemptTotal: 1275,
      bodyTotal: 1275,
      bodyPerRun: 842,
      graphNodes: 308,
      graphEdges: 1011,
    },
    "mention removal": {
      attemptTotal: 1262,
      bodyTotal: 1262,
      bodyPerRun: 838,
      graphNodes: 308,
      graphEdges: 1010,
    },
    "mention insertion": {
      attemptTotal: 1264,
      bodyTotal: 1264,
      bodyPerRun: 839,
      graphNodes: 308,
      graphEdges: 1011,
    },
    "same-count retarget": {
      attemptTotal: 1263,
      bodyTotal: 1263,
      bodyPerRun: 839,
      graphNodes: 308,
      graphEdges: 1010,
    },
    "comment append": {
      attemptTotal: 10,
      bodyTotal: 10,
      bodyPerRun: 10,
      graphNodes: 310,
      graphEdges: 1011,
    },
    "comment edit": {
      attemptTotal: 10,
      bodyTotal: 10,
      bodyPerRun: 10,
      graphNodes: 310,
      graphEdges: 1011,
    },
    "comment retraction": {
      attemptTotal: 10,
      bodyTotal: 10,
      bodyPerRun: 10,
      graphNodes: 310,
      graphEdges: 1011,
    },
    "link removal": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 310,
      graphEdges: 1011,
    },
    "unrelated sibling edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 310,
      graphEdges: 1011,
    },
    reopen: {
      attemptTotal: 1273,
      bodyTotal: 1273,
      bodyPerRun: 839,
      graphNodes: 310,
      graphEdges: 1011,
    },
  },
  "pivot/single-bucket/mentions-4/topics-128/all-backlinks": {
    initialization: {
      attemptTotal: 37590,
      bodyTotal: 37590,
      bodyPerRun: 842,
      graphNodes: 998,
      graphEdges: 37883,
    },
    "mention removal": {
      attemptTotal: 1262,
      bodyTotal: 1262,
      bodyPerRun: 838,
      graphNodes: 998,
      graphEdges: 37882,
    },
    "mention insertion": {
      attemptTotal: 1264,
      bodyTotal: 1264,
      bodyPerRun: 839,
      graphNodes: 998,
      graphEdges: 37883,
    },
    "same-count retarget": {
      attemptTotal: 1550,
      bodyTotal: 1550,
      bodyPerRun: 839,
      graphNodes: 998,
      graphEdges: 37883,
    },
    "comment append": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 998,
      graphEdges: 37883,
    },
    "comment edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 998,
      graphEdges: 37883,
    },
    "comment retraction": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 998,
      graphEdges: 37883,
    },
    "link removal": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 998,
      graphEdges: 37883,
    },
    "unrelated sibling edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 998,
      graphEdges: 37883,
    },
    reopen: {
      attemptTotal: 37586,
      bodyTotal: 37586,
      bodyPerRun: 839,
      graphNodes: 998,
      graphEdges: 37883,
    },
  },
  "pivot/high-degree/mentions-4/topics-128/topic-open": {
    initialization: {
      attemptTotal: 1280,
      bodyTotal: 1280,
      bodyPerRun: 846,
      graphNodes: 308,
      graphEdges: 1011,
    },
    "mention removal": {
      attemptTotal: 1270,
      bodyTotal: 1270,
      bodyPerRun: 845,
      graphNodes: 308,
      graphEdges: 1010,
    },
    "mention insertion": {
      attemptTotal: 1272,
      bodyTotal: 1272,
      bodyPerRun: 846,
      graphNodes: 308,
      graphEdges: 1011,
    },
    "same-count retarget": {
      attemptTotal: 1271,
      bodyTotal: 1271,
      bodyPerRun: 846,
      graphNodes: 308,
      graphEdges: 1010,
    },
    "comment append": {
      attemptTotal: 10,
      bodyTotal: 10,
      bodyPerRun: 10,
      graphNodes: 310,
      graphEdges: 1011,
    },
    "comment edit": {
      attemptTotal: 10,
      bodyTotal: 10,
      bodyPerRun: 10,
      graphNodes: 310,
      graphEdges: 1011,
    },
    "comment retraction": {
      attemptTotal: 10,
      bodyTotal: 10,
      bodyPerRun: 10,
      graphNodes: 310,
      graphEdges: 1011,
    },
    "link removal": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 310,
      graphEdges: 1011,
    },
    "unrelated sibling edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 310,
      graphEdges: 1011,
    },
    reopen: {
      attemptTotal: 1281,
      bodyTotal: 1281,
      bodyPerRun: 846,
      graphNodes: 310,
      graphEdges: 1011,
    },
  },
  "pivot/high-degree/mentions-4/topics-128/all-backlinks": {
    initialization: {
      attemptTotal: 38018,
      bodyTotal: 38018,
      bodyPerRun: 846,
      graphNodes: 998,
      graphEdges: 38307,
    },
    "mention removal": {
      attemptTotal: 1270,
      bodyTotal: 1270,
      bodyPerRun: 845,
      graphNodes: 998,
      graphEdges: 38306,
    },
    "mention insertion": {
      attemptTotal: 1272,
      bodyTotal: 1272,
      bodyPerRun: 846,
      graphNodes: 998,
      graphEdges: 38307,
    },
    "same-count retarget": {
      attemptTotal: 1558,
      bodyTotal: 1558,
      bodyPerRun: 846,
      graphNodes: 998,
      graphEdges: 38307,
    },
    "comment append": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 998,
      graphEdges: 38307,
    },
    "comment edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 998,
      graphEdges: 38307,
    },
    "comment retraction": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 998,
      graphEdges: 38307,
    },
    "link removal": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 998,
      graphEdges: 38307,
    },
    "unrelated sibling edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 998,
      graphEdges: 38307,
    },
    reopen: {
      attemptTotal: 38018,
      bodyTotal: 38018,
      bodyPerRun: 846,
      graphNodes: 998,
      graphEdges: 38307,
    },
  },
  "pivot/low-degree/mentions-16/topics-128/topic-open": {
    initialization: {
      attemptTotal: 2847,
      bodyTotal: 2847,
      bodyPerRun: 2536,
      graphNodes: 308,
      graphEdges: 889,
    },
    "mention removal": {
      attemptTotal: 2837,
      bodyTotal: 2837,
      bodyPerRun: 2535,
      graphNodes: 308,
      graphEdges: 888,
    },
    "mention insertion": {
      attemptTotal: 2840,
      bodyTotal: 2840,
      bodyPerRun: 2536,
      graphNodes: 308,
      graphEdges: 889,
    },
    "same-count retarget": {
      attemptTotal: 2838,
      bodyTotal: 2838,
      bodyPerRun: 2536,
      graphNodes: 308,
      graphEdges: 888,
    },
    "comment append": {
      attemptTotal: 10,
      bodyTotal: 10,
      bodyPerRun: 10,
      graphNodes: 310,
      graphEdges: 889,
    },
    "comment edit": {
      attemptTotal: 10,
      bodyTotal: 10,
      bodyPerRun: 10,
      graphNodes: 310,
      graphEdges: 889,
    },
    "comment retraction": {
      attemptTotal: 10,
      bodyTotal: 10,
      bodyPerRun: 10,
      graphNodes: 310,
      graphEdges: 889,
    },
    "link removal": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 310,
      graphEdges: 889,
    },
    "unrelated sibling edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 310,
      graphEdges: 889,
    },
    reopen: {
      attemptTotal: 2848,
      bodyTotal: 2848,
      bodyPerRun: 2536,
      graphNodes: 310,
      graphEdges: 889,
    },
  },
  "pivot/low-degree/mentions-16/topics-128/all-backlinks": {
    initialization: {
      attemptTotal: 41397,
      bodyTotal: 41397,
      bodyPerRun: 2536,
      graphNodes: 998,
      graphEdges: 39996,
    },
    "mention removal": {
      attemptTotal: 2837,
      bodyTotal: 2837,
      bodyPerRun: 2535,
      graphNodes: 998,
      graphEdges: 39995,
    },
    "mention insertion": {
      attemptTotal: 2840,
      bodyTotal: 2840,
      bodyPerRun: 2536,
      graphNodes: 998,
      graphEdges: 39996,
    },
    "same-count retarget": {
      attemptTotal: 3143,
      bodyTotal: 3143,
      bodyPerRun: 2536,
      graphNodes: 998,
      graphEdges: 39996,
    },
    "comment append": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 998,
      graphEdges: 39996,
    },
    "comment edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 998,
      graphEdges: 39996,
    },
    "comment retraction": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 998,
      graphEdges: 39996,
    },
    "link removal": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 998,
      graphEdges: 39996,
    },
    "unrelated sibling edit": {
      attemptTotal: 0,
      bodyTotal: 0,
      bodyPerRun: 0,
      graphNodes: 998,
      graphEdges: 39996,
    },
    reopen: {
      attemptTotal: 41397,
      bodyTotal: 41397,
      bodyPerRun: 2536,
      graphNodes: 998,
      graphEdges: 39996,
    },
  },
};
