/**
 * Guidance for checking a revision's effect through the existing release boundary.
 */
export const REVISION_VERIFICATION_GUIDANCE = [
  "Before reporting a revision done, verify the effect the user asked for. A successful revise_piece receipt establishes that source was applied, not that a rule changed any rows or that a style is readable.",
  "For a classifier or filter, the pattern-author reads the current source and wires read_piece_source's inputRef into an ordinary run_pattern check. Use the piece's bound inputs and the same readers, query scope, and existing filters. Evaluate the OLD and NEW predicates on the SAME bounded sample in one computation before revising. Report ready, sampleSize, beforeCount, afterCount, and changedCount (the number of rows whose inclusion changes, not just the difference between totals). Check pending, errors, and outputConcerns first: an unsettled, refused, or unavailable read is not an empty sample. A sample establishes only the effect on those sampled rows.",
  "Return the comparison's resultRef as verificationRef on the pattern-author return, including the failure branch when nothing changed. Keep the actual piece's resultRef separate. Counts, rows, sender names, and source text do not cross in that return. The parent reads verificationRef with ordinary run_pattern and resultSchema under the existing release rules; it uses only the values actually released, never numbers asserted in a child's prose or inferred from a name.",
  "A zero changedCount, empty sample, or unavailable verification is not completion: leave the rule unchanged and end with finish_task question. State the released finding (for example, excluded 0 of 37 sampled items) and ask which sender or kind of message should change. Do not invent examples that were not released, broaden the rule speculatively, or delegate repeated attempts to discover what the user meant. For a nonzero check, apply the tested rule, report the sampled delta in the final text, and distinguish a refresh warning from a verified running revision.",
  "For a styling change, use a supplied observation of the computed surface the piece renders on, such as its pane background, when available. Source colors do not establish that surface. When no such observation or permitted tool is available, say the rendered appearance was not checked; do not claim a contrast or render check succeeded. For rule verification blockers, the child returns the failure branch; only the parent calls finish_task.",
].join("\n\n");
