export {
  canonicalPieceAddress,
  decodePlan,
  deriveRollbackPlan,
  encodePlan,
  type PieceExpect,
  type PieceOp,
  type PiecePlan,
  type PiecePlanHeader,
  type PiecePlanRow,
  type PlanEnumeration,
  type RegisteredOutside,
  type RestoreOp,
  type RetargetOp,
  type RetargetSource,
  type SurveyProblem,
} from "./bulk-plan.ts";
export {
  collectLinkPaths,
  type DocumentChange,
  documentChanges,
  evaluateFixer,
  type Fixer,
  type FixerOutcome,
  type RepairOptions,
  repairPieces,
  type RepairReport,
  type RepairRow,
  type RepairVerdict,
} from "./bulk-repair.ts";
export {
  diffPlan,
  type PatternRef,
  type PieceDiffRow,
  type PieceDiffStatus,
  type PlanDiff,
} from "./bulk-diff.ts";
export {
  HOLDER_PHASE,
  LIST_PHASE,
  type PiecePin,
  type PieceSelector,
  type PlannedRetarget,
  readPiecePin,
  type SelectedPiece,
  selectPieces,
  type SurveyOptions,
  surveyPieces,
  type SurveyResult,
  type TallyEntry,
} from "./bulk-survey.ts";
export { PiecesController } from "./pieces-controller.ts";
export {
  type PatternCompatibilityReport,
  PieceController,
  type PiecePatternRef,
  type PiecePatternSourceRef,
  type PieceSourceAction,
  type PieceSourceActionResult,
  type PieceSourceCompatibilityIssues,
  type PreparedPieceSourceChange,
} from "./piece-controller.ts";
export {
  classifyOrigin,
  type PieceOrigin,
  PieceOriginError,
  type PieceOriginKind,
  type PieceSourceRevisionSource,
  type PieceSourceRevisionState,
  type PieceSourceState,
  readPieceOrigin,
  readPieceSourceMetadata,
  readPieceSourceRevision,
  readPieceSourceState,
  type ResolvedPieceOriginSource,
  resolvePieceOriginSource,
} from "./piece-origin.ts";
