export {
  type ApplyOptions,
  applyPlan,
  type ApplyReport,
  type ApplyRow,
  type ApplySessions,
  type ApplyVerdict,
  type PlanOperation,
  type ReferenceOp,
  type WorkRow,
} from "./bulk-apply.ts";
export {
  acceptUnretained,
  canonicalPieceAddress,
  decodePlan,
  deriveRollbackPlan,
  encodePlan,
  type PieceExpect,
  type PieceOp,
  type PiecePlan,
  type PiecePlanHeader,
  type PiecePlanRow,
  type PlanEnumeration,
  type RegisteredOutside,
  type RepairOp,
  type RestoreOp,
  type RetargetOp,
  type RetargetSource,
  type RollbackDerivationOptions,
  type SurveyProblem,
} from "./bulk-plan.ts";
export { type RollbackOptions, rollbackPieces } from "./bulk-rollback.ts";
export {
  readRestorableSource,
  type RestorableRevision,
  type RestorableSource,
  type RestoreOptions,
  type RestoreOutcome,
  restorePiece,
  type RestoreTarget,
  selectRestoreRevision,
} from "./piece-restore.ts";
export {
  assertPlanRunsFixer,
  collectLinkPaths,
  type DocumentChange,
  documentChanges,
  evaluateFixer,
  type Fixer,
  type FixerOutcome,
  type RepairOptions,
  repairPieces,
  type RepairReport,
  type RepairRow,
  type RepairVerdict,
} from "./bulk-repair.ts";
export {
  diffPlan,
  type PatternRef,
  type PieceDiffRow,
  type PieceDiffStatus,
  type PlanDiff,
} from "./bulk-diff.ts";
export {
  HOLDER_PHASE,
  isSourceRetained,
  LIST_PHASE,
  type PiecePin,
  type PieceSelector,
  type PlannedRetarget,
  readPiecePin,
  type SelectedPiece,
  selectPieces,
  type SurveyOptions,
  surveyPieces,
  type SurveyResult,
  type TallyEntry,
} from "./bulk-survey.ts";
export { PiecesController } from "./pieces-controller.ts";
export {
  type PatternCompatibilityReport,
  type PatternUpdateReceipt,
  PieceController,
  type PiecePatternRef,
  type PiecePatternSourceRef,
  type PieceSourceAction,
  type PieceSourceActionResult,
  PieceSourceChangedError,
  type PieceSourceCompatibilityIssues,
  type PreparedPieceSourceChange,
} from "./piece-controller.ts";
export {
  acceptEnteredOrigin,
  classifyOrigin,
  type PieceOrigin,
  PieceOriginError,
  type PieceOriginKind,
  type PieceSourceRevisionSource,
  type PieceSourceRevisionState,
  type PieceSourceState,
  readPieceOrigin,
  readPieceSourceMetadata,
  readPieceSourceRevision,
  readPieceSourceState,
  type ResolvedPieceOriginSource,
  resolvePieceOriginSource,
} from "./piece-origin.ts";
