import { expect } from "@std/expect";
import { describe, it } from "@std/testing/bdd";

import { generateCommonfabricTypes } from "./generate-commonfabric-types.ts";

/**
 * Tests for the `commonfabric` type generator.
 *
 * The first is a contract test: the checked-in
 * `assets/types/commonfabric.d.ts` is what the pattern compiler serves, and it
 * has to be what this generator produces. The rest pin the shape of that
 * output.
 *
 * These tests read files, so they run under the Deno test runner only. They
 * live beside the generator under `scripts/`, where the recursive deno-test
 * task finds them but the browser-bundled `test/*.test.ts` pass does not.
 */

const GENERATED_URL = new URL(
  "../assets/types/commonfabric.d.ts",
  import.meta.url,
);
const SOURCE_URL = new URL("../../api/index.ts", import.meta.url);

describe("generate-commonfabric-types", () => {
  describe("generateCommonfabricTypes()", () => {
    it("returns the text of the checked-in type module", async () => {
      expect(await generateCommonfabricTypes()).toBe(
        Deno.readTextFileSync(GENERATED_URL),
      );
    });

    it("returns text opening with the script's path and a do-not-edit line", async () => {
      const lines = (await generateCommonfabricTypes()).split("\n");
      expect(lines[0]).toBe(
        "// Generated by" +
          " packages/static/scripts/generate-commonfabric-types.ts.",
      );
      expect(lines[1]).toBe("// Do not edit by hand.");
    });

    it("returns text naming both the regenerate and the check task", async () => {
      const generated = await generateCommonfabricTypes();
      expect(generated).toContain("deno task gen-commonfabric-types");
      expect(generated).toContain("deno task check-commonfabric-types");
    });

    it("returns text ending with the pattern API module verbatim", async () => {
      const generated = await generateCommonfabricTypes();
      const source = Deno.readTextFileSync(SOURCE_URL);
      expect(generated.endsWith(source)).toBe(true);
      // The header is what precedes it, and nothing else is interposed.
      expect(generated.slice(0, -source.length)).toMatch(
        /^(\/\/[^\n]*\n)+\n$/,
      );
    });

    it("reads the module named by its argument", async () => {
      const path = await Deno.makeTempFile({ suffix: ".ts" });
      try {
        await Deno.writeTextFile(path, "export type Fake = never;\n");
        expect(await generateCommonfabricTypes(path)).toContain(
          "export type Fake = never;\n",
        );
      } finally {
        await Deno.remove(path);
      }
    });
  });
});
