#!/usr/bin/env -S deno run --allow-read --allow-write
import { fromFileUrl } from "@std/path";

import { cliMain, type GeneratedAsset } from "./generated-asset.ts";

/**
 * Generates `packages/static/assets/types/commonfabric.d.ts` from the public
 * pattern API (`packages/api/index.ts`).
 *
 * That file is the type module the pattern compiler serves for `commonfabric`,
 * and it is also what a reader opens to see the surface a pattern is written
 * against. Generating it puts a "do not edit by hand" line at the top of what
 * a reader opens, and gives the api module room to reach declarations that
 * live in other packages: the compiler serves each module as a single
 * self-contained text, so anything the api module takes from elsewhere has to
 * arrive as text in this file.
 *
 * Run with `--check` to fail when the checked-in file is out of date; run with
 * no arguments to rewrite it.
 */

const SCRIPT_REL_PATH =
  "packages/static/scripts/generate-commonfabric-types.ts";
const SOURCE_REL_PATH = "packages/api/index.ts";
const GEN_TASK = "deno task gen-commonfabric-types";
const CHECK_TASK = "deno task check-commonfabric-types";

const sourcePath = fromFileUrl(new URL("../../api/index.ts", import.meta.url));
const targetPath = fromFileUrl(
  new URL("../assets/types/commonfabric.d.ts", import.meta.url),
);

const HEADER = [
  `// Generated by ${SCRIPT_REL_PATH}.`,
  "// Do not edit by hand.",
  "//",
  "// The type module the pattern compiler serves for `commonfabric`, built",
  `// from ${SOURCE_REL_PATH}.`,
  "//",
  "// To regenerate after changing the pattern API, run (from packages/static):",
  `//   ${GEN_TASK}`,
  "// To verify it is up to date, run:",
  `//   ${CHECK_TASK}`,
].join("\n");

/** Builds the type module's text from the pattern API module. */
export async function generateCommonfabricTypes(
  source: string = sourcePath,
): Promise<string> {
  return `${HEADER}\n\n${await Deno.readTextFile(source)}`;
}

/** This script's asset. */
export const asset: GeneratedAsset = {
  target: targetPath,
  genTask: GEN_TASK,
  generate: generateCommonfabricTypes,
};

await cliMain(asset, Deno.args, import.meta.main);
