/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_commonfunction_free(a: number, b: number): void;
export function commonfunction_run(a: number, b: number): number;
export function __wbg_value_free(a: number, b: number): void;
export function __wbg_get_value_tag(a: number, b: number): void;
export function __wbg_set_value_tag(a: number, b: number, c: number): void;
export function __wbg_get_value_val(a: number): number;
export function __wbg_set_value_val(a: number, b: number): void;
export function value_new(a: number): number;
export function __wbg_commonruntime_free(a: number, b: number): void;
export function commonruntime_new(a: number, b: number): number;
export function commonruntime_instantiate(a: number, b: number): number;
export function __wbg_intounderlyingbytesource_free(a: number, b: number): void;
export function intounderlyingbytesource_type(a: number, b: number): void;
export function intounderlyingbytesource_autoAllocateChunkSize(a: number): number;
export function intounderlyingbytesource_start(a: number, b: number): void;
export function intounderlyingbytesource_pull(a: number, b: number): number;
export function intounderlyingbytesource_cancel(a: number): void;
export function __wbg_intounderlyingsource_free(a: number, b: number): void;
export function intounderlyingsource_pull(a: number, b: number): number;
export function intounderlyingsource_cancel(a: number): void;
export function __wbg_intounderlyingsink_free(a: number, b: number): void;
export function intounderlyingsink_write(a: number, b: number): number;
export function intounderlyingsink_close(a: number): number;
export function intounderlyingsink_abort(a: number, b: number): number;
export function __wbindgen_export_0(a: number, b: number): number;
export function __wbindgen_export_1(a: number, b: number, c: number, d: number): number;
export function __wbindgen_export_2(a: number, b: number, c: number): void;
export const __wbindgen_export_3: WebAssembly.Table;
export function __wbindgen_export_4(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_export_5(a: number): void;
export function __wbindgen_export_6(a: number, b: number, c: number, d: number): void;
