name: Jumble CI

on:
  push:
    branches: [main, denoify]
  pull_request:
    branches: [main]

jobs:
  jumble-build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.2.2"

      - name: Build
        working-directory: ./typescript/packages/jumble
        run: deno task build
        env:
          VITE_STORAGE_TYPE: "remote"
          TOOLSHED_API_URL: ${{ secrets.TOOLSHED_API_URL }}
          VITE_TOOLSHED_API_URL: ${{ secrets.TOOLSHED_API_URL }}

      - name: Tarballify dist
        working-directory: ./typescript/packages/jumble
        run: tar -czvf dist.tar.gz dist

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}.tar.gz
          path: ./typescript/packages/jumble/dist.tar.gz

      - uses: ryand56/r2-upload-action@v1.4
        if: github.ref == 'refs/heads/main'
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: ./typescript/packages/jumble/dist
          destination-dir: jumble/latest

      - uses: ryand56/r2-upload-action@v1.4
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: ./typescript/packages/jumble/dist
          destination-dir: jumble/${{ github.sha }}
