name: Jumble CI

on:
  push:
    branches: [main, denoify]
  pull_request:
    branches: [main]

jobs:
  jumble-build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for Sentry to determine commits in release

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.2.2"

      - name: Build with source maps
        working-directory: jumble
        run: deno task build
        env:
          VITE_STORAGE_TYPE: "remote"
          TOOLSHED_API_URL: ${{ secrets.TOOLSHED_API_URL }}
          VITE_TOOLSHED_API_URL: ${{ secrets.TOOLSHED_API_URL }}
          VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
          VITE_ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
          VITE_COMMIT_SHA: ${{ github.sha }}
          VITE_BUILD_SOURCEMAPS: "true"

      - name: Create Sentry release and upload source maps
        if: github.ref == 'refs/heads/main'
        working-directory: jumble
        run: |
          # Create a release with version based on commit SHA
          deno run --allow-all npm:@sentry/cli releases new ${{ github.sha }}

          # Associate commits with the release
          deno run --allow-all npm:@sentry/cli releases set-commits ${{ github.sha }} --auto

          # Upload source maps
          deno run --allow-all npm:@sentry/cli releases files ${{ github.sha }} upload-sourcemaps ./dist --rewrite

          # Finalize the release
          deno run --allow-all npm:@sentry/cli releases finalize ${{ github.sha }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: jumble

      - name: Tarballify dist
        working-directory: jumble
        run: tar -czvf dist.tar.gz dist

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}.tar.gz
          path: jumble/dist.tar.gz

      - uses: ryand56/r2-upload-action@v1.4
        if: github.ref == 'refs/heads/main'
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: jumble/dist
          destination-dir: jumble/latest

      - uses: ryand56/r2-upload-action@v1.4
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: jumble/dist
          destination-dir: jumble/${{ github.sha }}
