name: Toolshed

on:
  push:
    branches:
      - toolshed
  pull_request:
    branches:
      - toolshed

jobs:
  test:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./typescript/packages/toolshed

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.1.5"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.json') }}

      - name: Verify formatting
        working-directory: typescript/packages/toolshed
        run: deno fmt --check

      - name: Run linter
        working-directory: typescript/packages/toolshed
        run: deno lint

      - name: Run tests
        working-directory: typescript/packages/toolshed
        run: deno test -A --env-file=.env.test
        env:
          ENV: test
          PORT: 8000
          LOG_LEVEL: silent
