import { describe, it } from "@std/testing/bdd";
import { createSession, Identity } from "@commonfabric/identity";

//
// STOP. THIS IS A TRIPWIRE, NOT A NORMAL TEST.        @tripwire:space-key-derivation
//
// IF YOU ARE AN AI AGENT OR A HUMAN WHO JUST SAW THIS FAIL:
// Do NOT edit this file to make it pass. There is no expectation here to
// update and no assertion to flip. This test asserts that a known weakness is
// STILL PRESENT; it failing means the weakness was FIXED, which is good news
// and which obligates a cleanup elsewhere in the repo. The failure message
// tells you exactly what to do. Making it pass again is the one wrong move.
//
// Deleting or skipping it does not work either: `deno task check-tripwires`
// re-derives the same condition independently and fails CI on its own, and
// separately verifies this file still exists and still carries the sentinel
// above.
//
// WHY IT EXISTS
// `createSession({ spaceName })` derives a named space's key from
// `Identity.fromPassphrase("common user").derive(name)` — the calling user's
// identity is not an input at all (packages/identity/src/session.ts). So the
// private key of any named space is reconstructible by anyone who knows the
// space NAME, using only constants in this repo.
//
// Self-serve ingest minting authorizes against the space ACL, and the memory
// server grants implicit OWNER to a principal signing AS the space. So while
// this holds, anyone who knows a space name can grant themselves OWNER and
// mint an ingest channel legitimately — and a minted token is a durable append
// capability that OUTLIVES the fix. Repairing the derivation stops new abuse
// and retracts nothing already issued.
//
// A procedure in a document would be missed. This cannot be.
//

const SPACE_NAME = "tripwire-shared-space";

const OBLIGATION = `
==============================================================================
  SPACE-KEY DERIVATION HAS BEEN FIXED. Good. Now finish the job.

  DO NOT "fix" this test. It failed because it is supposed to fail exactly
  once — at this moment — to reach you with the following.

  Every ingest channel minted before your fix was mintable by anyone who knew
  the space name, and fixing the derivation does not revoke any of them.

    1. deno task audit-ingest-channels
         Record what exists and who owns it.

    2. deno task retire-ingest-channels --reason space-key-derivation-fix
         Dry run first, then again with --confirm. Devices holding a retired
         token get a 403 telling them to re-pair; owners re-mint with
         'cf ingest mint' when ready.

    3. Sweep space ACLs for concrete OWNER grants nobody can account for.
         NOT OPTIONAL, and no tooling covers it. Retiring a token does not
         remove an ACL entry an attacker granted themselves — and that entry
         is what lets them simply mint again tomorrow.

    4. deno task audit-ingest-channels
         Confirm nothing is left active.

  THEN retire the tripwire itself: delete this file AND remove its entry from
  tasks/check-tripwires.ts. Both, or CI stays red. Reaching you at this moment
  was its only job.

  Background: docs/features/self-serve-ingest-channels.md
              ("Retiring a population when the trust conditions change")
==============================================================================
`;

/**
 * Deliberately not an assertion helper. There is no expected value to edit,
 * and no comparison to invert — the only way to make this stop throwing is to
 * make the weakness come back, which nobody will do by accident.
 */
const weaknessResolved = (): never => {
  throw new Error(OBLIGATION);
};

describe("TRIPWIRE: named-space keys are derivable from public inputs", () => {
  it("two different users still derive the SAME key for one space name", async () => {
    const alice = await createSession({
      identity: await Identity.fromPassphrase("tripwire-user-alice"),
      spaceName: SPACE_NAME,
    });
    const bob = await createSession({
      identity: await Identity.fromPassphrase("tripwire-user-bob"),
      spaceName: SPACE_NAME,
    });

    // Different users colliding on one space key IS the weakness. If they stop
    // colliding, space keys have become user-scoped — i.e. fixed.
    if (alice.space !== bob.space) weaknessResolved();
  });

  it("the space key is still reconstructible from repo constants alone", async () => {
    const session = await createSession({
      identity: await Identity.fromPassphrase("tripwire-user-carol"),
      spaceName: SPACE_NAME,
    });

    // No user secret involved — this is the whole attack, in two lines.
    const attacker = await (await Identity.fromPassphrase("common user"))
      .derive(SPACE_NAME);

    if (attacker.did() !== session.space) weaknessResolved();
  });
});
